# Translations for Group 1: es, de, fr, zh_CN, pt_br, it

DATA = {
    'it': {
        "\n\nSanitized %d hardware keys for device compatibility.": "\n\nBonificate %d chiavi hardware per compatibilità dispositivo.",
        "(No subfolders)": "(Nessuna sottocartella)",
        "Archive: %s": "Archivio: %s",
        "Are you sure you want to restore this backup?\n\nAn automatic safety rollback snapshot will be created before any files are updated.": "Vuoi davvero ripristinare questo backup?\n\nVerrà creata un'istantanea di sicurezza prima di aggiornare i file.",
        "Backup & Restore Settings": "Impostazioni Backup e Ripristino",
        "Backup Folder:\n%s": "Cartella backup:\n%s",
        "Backup Name": "Nome backup",
        "Backup created successfully!\n\nFile: %s\nSize: %s\nArchived files: %d": "Backup creato con successo!\n\nFile: %s\nDimensione: %s\nFile archiviati: %d",
        "Backup received successfully!\n\nFile: %s": "Backup ricevuto con successo!\n\nFile: %s",
        "Backup restored successfully!": "Backup ripristinato con successo!",
        "Backup: Beam to Another Device": "Backup: Trasmetti a un altro dispositivo",
        "Backup: Create Backup": "Backup: Crea backup",
        "Backup: Open Manager": "Backup: Apri gestione",
        "Backup: Receive via Beam Code": "Backup: Ricevi con codice Beam",
        "Backup: Restore Backup": "Backup: Ripristina backup",
        "Beam Relay Server URL": "URL del server Beam",
        "Beam Relay Server:\n%s": "Server Beam:\n%s",
        "Beam code expired or not found. Please verify the 6-digit code on the sending device.": "Codice Beam scaduto o non trovato. Verifica il codice a 6 cifre sul dispositivo mittente.",
        "Beam code must be exactly %d digits.": "Il codice Beam deve contenere esattamente %d cifre.",
        "Beam code ready!": "Codice Beam pronto!",
        "Beam reception failed:\n%s": "Ricezione Beam fallita:\n%s",
        "Beam to Another Device...": "Trasmetti a un altro dispositivo...",
        "Beam to Device": "Trasmetti al dispositivo",
        "Beam to Device...": "Trasmetti al dispositivo...",
        "Beam transfer canceled.": "Trasferimento Beam annullato.",
        "Beam upload failed:\n%s": "Invio Beam fallito:\n%s",
        "Browse Folder": "Sfoglia cartella",
        "Browse Other Folder...": "Sfoglia un'altra cartella...",
        "Cancel": "Annulla",
        "Cancel Transfer": "Annulla trasferimento",
        "Choose Backup Folder": "Scegli cartella backup",
        "Clean Slate (Remove unlisted plugins)": "Installazione pulita (rimuovi plugin non inclusi)",
        "Clear All": "Deseleziona tutto",
        "Close": "Chiudi",
        "Code expires in 15 minutes\nSingle-use end-to-end encrypted": "Il codice scade in 15 minuti\nCrittografia end-to-end monouso",
        "Connecting and downloading backup archive...": "Connessione e download dell'archivio...",
        "Connecting to Beam relay and downloading backup...\nPlease wait.": "Connessione al server Beam e download...\nAttendere prego.",
        "Connecting to Beam relay...": "Connessione al server Beam...",
        "Corrupted or empty Beam payload.": "Dati Beam corrotti o vuoti.",
        "Could not read file: %s": "Impossibile leggere il file: %s",
        "Could not write file: %s": "Impossibile scrivere il file: %s",
        "Create": "Crea",
        "Create Backup": "Crea backup",
        "Create Backup...": "Crea backup...",
        "Create subfolder in '%s':": "Crea sottocartella in '%s':",
        "Create, manage, and restore modular KOReader backups with intelligent cross-device hardware sanitization and disaster recovery.": "Crea, gestisci e ripristina backup modulari di KOReader con adattamento hardware intelligente tra dispositivi e ripristino d'emergenza.",
        "Creating backup archive...\nPlease wait.": "Creazione archivio di backup...\nAttendere prego.",
        "Default Format: .%s (Tap to toggle)": "Formato predefinito: .%s (tocca per cambiare)",
        "Delete": "Elimina",
        "Delete Backup": "Elimina backup",
        "Delete backup '%s'?\nThis action cannot be undone.": "Eliminare il backup '%s'?\nQuesta azione non può essere annullata.",
        "Device Backup & Restore": "Backup e Ripristino Dispositivo",
        "Dictionaries & OCR Data": "Dizionari e dati OCR",
        "Done": "Fatto",
        "Download failed (HTTP %s): %s": "Download non riuscito (HTTP %s): %s",
        "Encrypting backup and uploading to Beam relay...\nPlease wait.": "Crittografia e invio al server Beam...\nAttendere prego.",
        "Encrypting backup archive...": "Crittografia archivio di backup...",
        "Enter custom filename (without extension):": "Inserisci nome file (senza estensione):",
        "Enter the 6-digit Beam code from the sending device:": "Inserisci il codice Beam a 6 cifre del dispositivo mittente:",
        "Extraction failed: %s": "Estrazione fallita: %s",
        "Failed to create backup:\n%s": "Creazione backup non riuscita:\n%s",
        "Failed to create folder.": "Creazione cartella non riuscita.",
        "Failed to inspect archive:\n": "Analisi archivio non riuscita:\n",
        "Fonts": "Caratteri",
        "Format: .%s": "Formato: .%s",
        "HTTPS address of the ephemeral Beam relay:": "Indirizzo HTTPS del server temporaneo Beam:",
        "Invalid Beam archive format.": "Formato archivio Beam non valido.",
        "Invalid Beam code or corrupted data.": "Codice Beam non valido o dati corrotti.",
        "Invalid filename in Beam payload.": "Nome file non valido nei dati Beam.",
        "Manage Backups": "Gestisci backup",
        "Manage Backups...": "Gestisci backup...",
        "Name: %s": "Nome: %s",
        "New Folder": "Nuova cartella",
        "Next": "Avanti",
        "No backup files found in:\n%s": "Nessun backup trovato in:\n%s",
        "No backup files found in:\n%s\n\nWould you like to browse a different folder?": "Nessun backup trovato in:\n%s\n\nVuoi sfogliare un'altra cartella?",
        "No backup files found in:\n%s\n\nWould you like to create a new backup now?": "Nessun backup trovato in:\n%s\n\nVuoi creare un nuovo backup adesso?",
        "No backup files found.": "Nessun file di backup trovato.",
        "No rollback snapshot available to undo.": "Nessun punto di ripristino disponibile per annullare.",
        "Number of rolling backups to keep (0 = unlimited):": "Numero di backup rotativi da mantenere (0 = illimitati):",
        "OK": "OK",
        "On the receiving device, open\n'Receive via Beam Code' and enter:": "Sul dispositivo ricevente, apri\n'Ricevi con codice Beam' e inserisci:",
        "Patches": "Patch",
        "Please enter a 6-digit Beam code.": "Inserisci un codice Beam di 6 cifre.",
        "Pre-flight check failed: %s": "Controllo preliminare fallito: %s",
        "Preparing and encrypting backup archive...": "Preparazione e crittografia archivio...",
        "Previous": "Indietro",
        "Reading History & Stats": "Cronologia e statistiche di lettura",
        "Reading Progress & Notes": "Avanzamento di lettura e note",
        "Receive & Restore": "Ricevi e ripristina",
        "Receive via Beam Code": "Ricevi con codice Beam",
        "Receive via Beam Code...": "Ricevi con codice Beam...",
        "Recommended": "Consigliato",
        "Registering code with Beam relay...": "Registrazione codice sul server Beam...",
        "Reset Default": "Ripristina predefinito",
        "Restart KOReader now to apply all changes?": "Riavviare KOReader per applicare le modifiche?",
        "Restart later": "Riavvia dopo",
        "Restart now": "Riavvia ora",
        "Restore Backup": "Ripristina backup",
        "Restore Backup...": "Ripristina backup...",
        "Restore Now": "Ripristina ora",
        "Restore completed.": "Ripristino completato.",
        "Restore failed: ": "Ripristino fallito: ",
        "Restore: %s": "Ripristina: %s",
        "Restoring backup...\nPlease wait.": "Ripristino del backup in corso...\nAttendere prego.",
        "Retention Limit": "Limite conservazione",
        "Retention Limit: Keep newest %d backups": "Limite: conserva i %d backup più recenti",
        "Revert to the pre-restore rollback snapshot?\n\nThis will undo the last restore and return your settings and patches to their prior state.\n\nKOReader will restart immediately.": "Tornare all'istantanea precedente al ripristino?\n\nQuesto annullerà l'ultimo ripristino e riporterà le impostazioni allo stato precedente.\n\nKOReader si riavvierà immediatamente.",
        "Reverting to rollback snapshot...": "Ripristino dell'istantanea precedente...",
        "Sanitize Hardware Settings": "Bonifica impostazioni hardware",
        "Save": "Salva",
        "Screensavers": "Salvaschermo",
        "Select All": "Seleziona tutto",
        "Select Backup Folder": "Seleziona cartella backup",
        "Select Backup to Beam": "Seleziona backup da trasmettere",
        "Select Backup to Restore": "Seleziona backup da ripristinare",
        "Select This Folder": "Seleziona questa cartella",
        "Set Name": "Imposta nome",
        "Settings & UI Gestures": "Impostazioni e gesti interfaccia",
        "Settings...": "Impostazioni...",
        "Source directory does not exist: %s": "La cartella di origine non esiste: %s",
        "Style Tweaks": "Regolazioni stile",
        "Successfully reverted to rollback snapshot.": "Ripristino dell'istantanea riuscito con successo.",
        "Undo Last Restore": "Annulla ultimo ripristino",
        "Undo Restore": "Annulla ripristino",
        "Undo failed: ": "Annullamento non riuscito: ",
        "Upload failed (HTTP %s): %s": "Invio non riuscito (HTTP %s): %s",
        "Uploading backup archive...": "Invio dell'archivio in corso...",
        "User Plugins": "Plugin utente",
        "[Up]  ..  (Parent folder)": "[Su]  ..  (Cartella superiore)",
        "btn_cancel": "Annulla",
        "btn_close": "Chiudi",
        "btn_create": "Crea",
        "btn_ok": "OK",
        "btn_restore": "Ripristina",
        "btn_settings": "Impostazioni...",
        "plugin_desc": "Crea, gestisci e ripristina backup modulari di KOReader con adattamento hardware intelligente tra dispositivi e ripristino d'emergenza.",
        "plugin_name": "Backup e Ripristino Dispositivo"
    }
}
