# Translations for Group 3: tr, hu, sk, sr, ar, id

DATA = {
    'tr': {
        "\n\nSanitized %d hardware keys for device compatibility.": "\n\nCihaz uyumluluğu için %d donanım anahtarı temizlendi.",
        "(No subfolders)": "(Alt klasör yok)",
        "Archive: %s": "Arşiv: %s",
        "Are you sure you want to restore this backup?\n\nAn automatic safety rollback snapshot will be created before any files are updated.": "Bu yedeği geri yüklemek istediğinizden emin misiniz?\n\nDosyalar güncellenmeden önce otomatik güvenlik geri alma noktası oluşturulacaktır.",
        "Backup & Restore Settings": "Yedekleme ve Geri Yükleme Ayarları",
        "Backup Folder:\n%s": "Yedek Klasörü:\n%s",
        "Backup Name": "Yedek Adı",
        "Backup created successfully!\n\nFile: %s\nSize: %s\nArchived files: %d": "Yedek başarıyla oluşturuldu!\n\nDosya: %s\nBoyut: %s\nArşivlenen dosya: %d",
        "Backup received successfully!\n\nFile: %s": "Yedek başarıyla alındı!\n\nDosya: %s",
        "Backup restored successfully!": "Yedek başarıyla geri yüklendi!",
        "Backup: Beam to Another Device": "Yedek: Başka Cihaza Işınla",
        "Backup: Create Backup": "Yedek: Yedek Oluştur",
        "Backup: Open Manager": "Yedek: Yöneticiyi Aç",
        "Backup: Receive via Beam Code": "Yedek: Beam Kodu ile Al",
        "Backup: Restore Backup": "Yedek: Yedeği Geri Yükle",
        "Beam Relay Server URL": "Beam Aktarım Sunucusu URL'si",
        "Beam Relay Server:\n%s": "Beam Aktarım Sunucusu:\n%s",
        "Beam code expired or not found. Please verify the 6-digit code on the sending device.": "Beam kodunun süresi dolmuş veya bulunamadı. Gönderen cihazdaki 6 haneli kodu doğrulayın.",
        "Beam code must be exactly %d digits.": "Beam kodu tam olarak %d basamaklı olmalıdır.",
        "Beam code ready!": "Beam kodu hazır!",
        "Beam reception failed:\n%s": "Beam alımı başarısız:\n%s",
        "Beam to Another Device...": "Başka Cihaza Işınla...",
        "Beam to Device": "Cihaza Işınla",
        "Beam to Device...": "Cihaza Işınla...",
        "Beam transfer canceled.": "Beam aktarımı iptal edildi.",
        "Beam upload failed:\n%s": "Beam yüklemesi başarısız:\n%s",
        "Browse Folder": "Klasöre Göz At",
        "Browse Other Folder...": "Başka Klasöre Göz At...",
        "Cancel": "İptal",
        "Cancel Transfer": "Aktarımı İptal Et",
        "Choose Backup Folder": "Yedek Klasörünü Seç",
        "Clean Slate (Remove unlisted plugins)": "Temiz Kurulum (listelenmeyen eklentileri kaldır)",
        "Clear All": "Tümünü Temizle",
        "Close": "Kapat",
        "Code expires in 15 minutes\nSingle-use end-to-end encrypted": "Kod 15 dakika içinde sona erer\nTek kullanımlık uçtan uca şifreli",
        "Connecting and downloading backup archive...": "Bağlanılıyor ve yedek arşivi indiriliyor...",
        "Connecting to Beam relay and downloading backup...\nPlease wait.": "Beam sunucusuna bağlanılıyor ve yedek indiriliyor...\nLütfen bekleyin.",
        "Connecting to Beam relay...": "Beam sunucusuna bağlanılıyor...",
        "Corrupted or empty Beam payload.": "Bozuk veya boş Beam verisi.",
        "Could not read file: %s": "Dosya okunamadı: %s",
        "Could not write file: %s": "Dosya yazılamadı: %s",
        "Create": "Oluştur",
        "Create Backup": "Yedek Oluştur",
        "Create Backup...": "Yedek Oluştur...",
        "Create subfolder in '%s':": "'%s' içinde alt klasör oluştur:",
        "Create, manage, and restore modular KOReader backups with intelligent cross-device hardware sanitization and disaster recovery.": "Cihazlar arası akıllı donanım uyumlulaştırması ve felaket kurtarma ile modüler KOReader yedekleri oluşturun, yönetin ve geri yükleyin.",
        "Creating backup archive...\nPlease wait.": "Yedek arşivi oluşturuluyor...\nLütfen bekleyin.",
        "Default Format: .%s (Tap to toggle)": "Varsayılan Biçim: .%s (Değiştirmek için dokunun)",
        "Delete": "Sil",
        "Delete Backup": "Yedeği Sil",
        "Delete backup '%s'?\nThis action cannot be undone.": "'%s' yedeği silinsin mi?\nBu işlem geri alınamaz.",
        "Device Backup & Restore": "Cihaz Yedekleme ve Geri Yükleme",
        "Dictionaries & OCR Data": "Sözlükler ve OCR Verileri",
        "Done": "Tamamlandı",
        "Download failed (HTTP %s): %s": "İndirme başarısız (HTTP %s): %s",
        "Encrypting backup and uploading to Beam relay...\nPlease wait.": "Yedek şifreleniyor ve Beam sunucusuna yükleniyor...\nLütfen bekleyin.",
        "Encrypting backup archive...": "Yedek arşivi şifreleniyor...",
        "Enter custom filename (without extension):": "Özel dosya adı girin (uzantı olmadan):",
        "Enter the 6-digit Beam code from the sending device:": "Gönderen cihazdaki 6 haneli Beam kodunu girin:",
        "Extraction failed: %s": "Çıkarma başarısız: %s",
        "Failed to create backup:\n%s": "Yedek oluşturulamadı:\n%s",
        "Failed to create folder.": "Klasör oluşturulamadı.",
        "Failed to inspect archive:\n": "Arşiv incelenemedi:\n",
        "Fonts": "Yazı Tipleri",
        "Format: .%s": "Biçim: .%s",
        "HTTPS address of the ephemeral Beam relay:": "Geçici Beam aktarım sunucusunun HTTPS adresi:",
        "Invalid Beam archive format.": "Geçersiz Beam arşiv biçimi.",
        "Invalid Beam code or corrupted data.": "Geçersiz Beam kodu veya bozuk veri.",
        "Invalid filename in Beam payload.": "Beam yükünde geçersiz dosya adı.",
        "Manage Backups": "Yedekleri Yönet",
        "Manage Backups...": "Yedekleri Yönet...",
        "Name: %s": "Ad: %s",
        "New Folder": "Yeni Klasör",
        "Next": "İleri",
        "No backup files found in:\n%s": "Şurada yedek dosyası bulunamadı:\n%s",
        "No backup files found in:\n%s\n\nWould you like to browse a different folder?": "Şurada yedek bulunamadı:\n%s\n\nFarklı bir klasöre göz atmak ister misiniz?",
        "No backup files found in:\n%s\n\nWould you like to create a new backup now?": "Şurada yedek bulunamadı:\n%s\n\nŞimdi yeni bir yedek oluşturmak ister misiniz?",
        "No backup files found.": "Yedek dosyası bulunamadı.",
        "No rollback snapshot available to undo.": "Geri alınacak kurtarma noktası yok.",
        "Number of rolling backups to keep (0 = unlimited):": "Tutulacak döngüsel yedek sayısı (0 = sınırsız):",
        "OK": "Tamam",
        "On the receiving device, open\n'Receive via Beam Code' and enter:": "Alıcı cihazda 'Beam Kodu ile Al'\nseçeneğini açın ve girin:",
        "Patches": "Yamalar",
        "Please enter a 6-digit Beam code.": "Lütfen 6 haneli bir Beam kodu girin.",
        "Pre-flight check failed: %s": "Ön denetim başarısız: %s",
        "Preparing and encrypting backup archive...": "Yedek arşivi hazırlanıyor ve şifreleniyor...",
        "Previous": "Önceki",
        "Reading History & Stats": "Okuma Geçmişi ve İstatistikler",
        "Reading Progress & Notes": "Okuma İlerlemesi ve Notlar",
        "Receive & Restore": "Al ve Geri Yükle",
        "Receive via Beam Code": "Beam Kodu ile Al",
        "Receive via Beam Code...": "Beam Kodu ile Al...",
        "Recommended": "Önerilen",
        "Registering code with Beam relay...": "Kod Beam sunucusuna kaydediliyor...",
        "Reset Default": "Varsayılana Sıfırla",
        "Restart KOReader now to apply all changes?": "Değişiklikleri uygulamak için KOReader yeniden başlatılsın mı?",
        "Restart later": "Daha sonra",
        "Restart now": "Yeniden başlat",
        "Restore Backup": "Yedeği Geri Yükle",
        "Restore Backup...": "Yedeği Geri Yükle...",
        "Restore Now": "Şimdi Geri Yükle",
        "Restore completed.": "Geri yükleme tamamlandı.",
        "Restore failed: ": "Geri yükleme başarısız: ",
        "Restore: %s": "Geri yükle: %s",
        "Restoring backup...\nPlease wait.": "Yedek geri yükleniyor...\nLütfen bekleyin.",
        "Retention Limit": "Saklama Limiti",
        "Retention Limit: Keep newest %d backups": "Saklama limiti: En yeni %d yedeği sakla",
        "Revert to the pre-restore rollback snapshot?\n\nThis will undo the last restore and return your settings and patches to their prior state.\n\nKOReader will restart immediately.": "Geri yükleme öncesi kurtarma noktasına dönülsün mü?\n\nBu son geri yüklemeyi geri alacak ve ayarlarınızı önceki durumuna getirecektir.\n\nKOReader hemen yeniden başlatılacak.",
        "Reverting to rollback snapshot...": "Kurtarma noktasına geri dönülüyor...",
        "Sanitize Hardware Settings": "Donanım Ayarlarını Temizle",
        "Save": "Kaydet",
        "Screensavers": "Ekran Koruyucular",
        "Select All": "Tümünü Seç",
        "Select Backup Folder": "Yedek Klasörünü Seç",
        "Select Backup to Beam": "Işınlanacak Yedeği Seç",
        "Select Backup to Restore": "Geri Yüklenecek Yedeği Seç",
        "Select This Folder": "Bu Klasörü Seç",
        "Set Name": "Adı Belirle",
        "Settings & UI Gestures": "Ayarlar ve Arayüz Hareketleri",
        "Settings...": "Ayarlar...",
        "Source directory does not exist: %s": "Kaynak dizin mevcut değil: %s",
        "Style Tweaks": "Stil İnce Ayarları",
        "Successfully reverted to rollback snapshot.": "Kurtarma noktasına başarıyla dönüldü.",
        "Undo Last Restore": "Son Geri Yüklemeyi Geri Al",
        "Undo Restore": "Geri Yüklemeyi Geri Al",
        "Undo failed: ": "Geri alma başarısız: ",
        "Upload failed (HTTP %s): %s": "Yükleme başarısız (HTTP %s): %s",
        "Uploading backup archive...": "Yedek arşivi yükleniyor...",
        "User Plugins": "Kullanıcı Eklentileri",
        "[Up]  ..  (Parent folder)": "[Yukarı]  ..  (Üst klasör)",
        "btn_cancel": "İptal",
        "btn_close": "Kapat",
        "btn_create": "Oluştur",
        "btn_ok": "Tamam",
        "btn_restore": "Geri Yükle",
        "btn_settings": "Ayarlar...",
        "plugin_desc": "Cihazlar arası akıllı donanım uyumlulaştırması ve felaket kurtarma ile modüler KOReader yedekleri oluşturun, yönetin ve geri yükleyin.",
        "plugin_name": "Cihaz Yedekleme ve Geri Yükleme"
    },
    'hu': {
        "\n\nSanitized %d hardware keys for device compatibility.": "\n\n%d hardverkulcs tisztítva az eszközkompatibilitás érdekében.",
        "(No subfolders)": "(Nincsenek almappák)",
        "Archive: %s": "Archívum: %s",
        "Are you sure you want to restore this backup?\n\nAn automatic safety rollback snapshot will be created before any files are updated.": "Biztosan visszaállítja ezt a biztonsági mentést?\n\nA fájlok frissítése előtt automatikus biztonsági visszaállítási pont készül.",
        "Backup & Restore Settings": "Mentés és visszaállítás beállításai",
        "Backup Folder:\n%s": "Mentési mappa:\n%s",
        "Backup Name": "Mentés neve",
        "Backup created successfully!\n\nFile: %s\nSize: %s\nArchived files: %d": "A biztonsági mentés sikeresen elkészült!\n\nFájl: %s\nMéret: %s\nArchivált fájlok: %d",
        "Backup received successfully!\n\nFile: %s": "A mentés sikeresen megérkezett!\n\nFájl: %s",
        "Backup restored successfully!": "A biztonsági mentés sikeresen visszaállítva!",
        "Backup: Beam to Another Device": "Mentés: Átsugárzás másik eszközre",
        "Backup: Create Backup": "Mentés: Mentés létrehozása",
        "Backup: Open Manager": "Mentés: Kezelő megnyitása",
        "Backup: Receive via Beam Code": "Mentés: Fogadás Beam-kóddal",
        "Backup: Restore Backup": "Mentés: Mentés visszaállítása",
        "Beam Relay Server URL": "Beam továbbító szerver URL",
        "Beam Relay Server:\n%s": "Beam szerver:\n%s",
        "Beam code expired or not found. Please verify the 6-digit code on the sending device.": "A Beam-kód lejárt vagy nem található. Kérjük, ellenőrizze a 6 jegyű kódot a küldő eszközön.",
        "Beam code must be exactly %d digits.": "A Beam-kódnak pontosan %d számjegyből kell állnia.",
        "Beam code ready!": "A Beam-kód készen áll!",
        "Beam reception failed:\n%s": "A Beam fogadás sikertelen:\n%s",
        "Beam to Another Device...": "Átsugárzás másik eszközre...",
        "Beam to Device": "Átsugárzás eszközre",
        "Beam to Device...": "Átsugárzás eszközre...",
        "Beam transfer canceled.": "A Beam átvitel megszakítva.",
        "Beam upload failed:\n%s": "A Beam feltöltés sikertelen:\n%s",
        "Browse Folder": "Mappa böngészése",
        "Browse Other Folder...": "Másik mappa böngészése...",
        "Cancel": "Mégse",
        "Cancel Transfer": "Átvitel megszakítása",
        "Choose Backup Folder": "Mentési mappa kiválasztása",
        "Clean Slate (Remove unlisted plugins)": "Tiszta telepítés (nem listázott bővítmények törlése)",
        "Clear All": "Kijelölések törlése",
        "Close": "Bezárás",
        "Code expires in 15 minutes\nSingle-use end-to-end encrypted": "A kód 15 percig érvényes\nEgyszeri végpontok közötti titkosítás",
        "Connecting and downloading backup archive...": "Csatlakozás és archívum letöltése...",
        "Connecting to Beam relay and downloading backup...\nPlease wait.": "Csatlakozás a Beam szerverhez és letöltés...\nKérjük, várjon.",
        "Connecting to Beam relay...": "Csatlakozás a Beam szerverhez...",
        "Corrupted or empty Beam payload.": "Sérült vagy üres Beam adatcsomag.",
        "Could not read file: %s": "A fájl nem olvasható: %s",
        "Could not write file: %s": "A fájl nem írható: %s",
        "Create": "Létrehozás",
        "Create Backup": "Mentés létrehozása",
        "Create Backup...": "Mentés létrehozása...",
        "Create subfolder in '%s':": "Almappa létrehozása a következőben: '%s':",
        "Create, manage, and restore modular KOReader backups with intelligent cross-device hardware sanitization and disaster recovery.": "Moduláris KOReader mentések létrehozása, kezelése és visszaállítása intelligens hardveres illesztéssel és katasztrófa utáni helyreállítással.",
        "Creating backup archive...\nPlease wait.": "Mentési archívum létrehozása...\nKérjük, várjon.",
        "Default Format: .%s (Tap to toggle)": "Alapértelmezett formátum: .%s (érintse meg a váltáshoz)",
        "Delete": "Törlés",
        "Delete Backup": "Mentés törlése",
        "Delete backup '%s'?\nThis action cannot be undone.": "Törli a(z) '%s' mentést?\nEz a művelet nem vonható vissza.",
        "Device Backup & Restore": "Eszköz mentése és visszaállítása",
        "Dictionaries & OCR Data": "Szótárak és OCR adatok",
        "Done": "Kész",
        "Download failed (HTTP %s): %s": "Letöltés sikertelen (HTTP %s): %s",
        "Encrypting backup and uploading to Beam relay...\nPlease wait.": "Mentés titkosítása és feltöltése a Beam szerverre...\nKérjük, várjon.",
        "Encrypting backup archive...": "Mentési archívum titkosítása...",
        "Enter custom filename (without extension):": "Adjon meg egyéni fájlnevet (kiterjesztés nélkül):",
        "Enter the 6-digit Beam code from the sending device:": "Adja meg a küldő eszköz 6 jegyű Beam-kódját:",
        "Extraction failed: %s": "Kicsomagolás sikertelen: %s",
        "Failed to create backup:\n%s": "Nem sikerült létrehozni a mentést:\n%s",
        "Failed to create folder.": "A mappa létrehozása sikertelen.",
        "Failed to inspect archive:\n": "Az archívum ellenőrzése sikertelen:\n",
        "Fonts": "Betűtípusok",
        "Format: .%s": "Formátum: .%s",
        "HTTPS address of the ephemeral Beam relay:": "Az ideiglenes Beam továbbító szerver HTTPS címe:",
        "Invalid Beam archive format.": "Érvénytelen Beam archívumformátum.",
        "Invalid Beam code or corrupted data.": "Érvénytelen Beam-kód vagy sérült adatok.",
        "Invalid filename in Beam payload.": "Érvénytelen fájlnév a Beam adatcsomagban.",
        "Manage Backups": "Mentések kezelése",
        "Manage Backups...": "Mentések kezelése...",
        "Name: %s": "Név: %s",
        "New Folder": "Új mappa",
        "Next": "Következő",
        "No backup files found in:\n%s": "Nem találhatók mentési fájlok itt:\n%s",
        "No backup files found in:\n%s\n\nWould you like to browse a different folder?": "Nem található mentés itt:\n%s\n\nSzeretne másik mappát tallózni?",
        "No backup files found in:\n%s\n\nWould you like to create a new backup now?": "Nem található mentés itt:\n%s\n\nSzeretne létrehozni egyet most?",
        "No backup files found.": "Nem találhatók mentési fájlok.",
        "No rollback snapshot available to undo.": "Nem áll rendelkezésre visszaállítási pont a visszavonáshoz.",
        "Number of rolling backups to keep (0 = unlimited):": "Megtartandó mentések száma (0 = korlátlan):",
        "OK": "OK",
        "On the receiving device, open\n'Receive via Beam Code' and enter:": "A fogadó eszközön nyissa meg a\n'Fogadás Beam-kóddal' menüt, és írja be:",
        "Patches": "Javítások",
        "Please enter a 6-digit Beam code.": "Kérjük, adjon meg egy 6 jegyű Beam-kódot.",
        "Pre-flight check failed: %s": "Előzetes ellenőrzés sikertelen: %s",
        "Preparing and encrypting backup archive...": "Mentési archívum előkészítése és titkosítása...",
        "Previous": "Előző",
        "Reading History & Stats": "Olvasási előzmények és statisztikák",
        "Reading Progress & Notes": "Olvasási haladás és jegyzetek",
        "Receive & Restore": "Fogadás és visszaállítás",
        "Receive via Beam Code": "Fogadás Beam-kóddal",
        "Receive via Beam Code...": "Fogadás Beam-kóddal...",
        "Recommended": "Ajánlott",
        "Registering code with Beam relay...": "Kód regisztrálása a Beam szerveren...",
        "Reset Default": "Alapértelmezés visszaállítása",
        "Restart KOReader now to apply all changes?": "Újraindítja a KOReader-t a módosítások alkalmazásához?",
        "Restart later": "Újraindítás később",
        "Restart now": "Újraindítás most",
        "Restore Backup": "Mentés visszaállítása",
        "Restore Backup...": "Mentés visszaállítása...",
        "Restore Now": "Visszaállítás most",
        "Restore completed.": "A visszaállítás befejeződött.",
        "Restore failed: ": "A visszaállítás sikertelen: ",
        "Restore: %s": "Visszaállítás: %s",
        "Restoring backup...\nPlease wait.": "Mentés visszaállítása...\nKérjük, várjon.",
        "Retention Limit": "Megőrzési korlát",
        "Retention Limit: Keep newest %d backups": "Megőrzés: a legújabb %d mentés megtartása",
        "Revert to the pre-restore rollback snapshot?\n\nThis will undo the last restore and return your settings and patches to their prior state.\n\nKOReader will restart immediately.": "Visszatér a visszaállítás előtti állapothoz?\n\nEz visszavonja az utolsó visszaállítást, és visszaállítja a korábbi beállításokat és javításokat.\n\nA KOReader azonnal újraindul.",
        "Reverting to rollback snapshot...": "Visszatérés a visszaállítási ponthoz...",
        "Sanitize Hardware Settings": "Hardverbeállítások megtisztítása",
        "Save": "Mentés",
        "Screensavers": "Képernyőkímélők",
        "Select All": "Összes kijelölése",
        "Select Backup Folder": "Mentési mappa kiválasztása",
        "Select Backup to Beam": "Átsugárzandó mentés kiválasztása",
        "Select Backup to Restore": "Visszaállítandó mentés kiválasztása",
        "Select This Folder": "E mappa kiválasztása",
        "Set Name": "Név megadása",
        "Settings & UI Gestures": "Beállítások és kézmozdulatok",
        "Settings...": "Beállítások...",
        "Source directory does not exist: %s": "A forráskönyvtár nem létezik: %s",
        "Style Tweaks": "Stílus finomhangolások",
        "Successfully reverted to rollback snapshot.": "Sikeresen visszatért a visszaállítási ponthoz.",
        "Undo Last Restore": "Utolsó visszaállítás visszavonása",
        "Undo Restore": "Visszaállítás visszavonása",
        "Undo failed: ": "A visszavonás sikertelen: ",
        "Upload failed (HTTP %s): %s": "Feltöltés sikertelen (HTTP %s): %s",
        "Uploading backup archive...": "Mentési archívum feltöltése...",
        "User Plugins": "Felhasználói bővítmények",
        "[Up]  ..  (Parent folder)": "[Fel]  ..  (Szülőmappa)",
        "btn_cancel": "Mégse",
        "btn_close": "Bezárás",
        "btn_create": "Létrehozás",
        "btn_ok": "OK",
        "btn_restore": "Visszaállítás",
        "btn_settings": "Beállítások...",
        "plugin_desc": "Moduláris KOReader mentések létrehozása, kezelése és visszaállítása intelligens hardveres illesztéssel és katasztrófa utáni helyreállítással.",
        "plugin_name": "Eszköz mentése és visszaállítása"
    },
    'sk': {
        "\n\nSanitized %d hardware keys for device compatibility.": "\n\nVyčistených %d hardvérových kľúčov pre kompatibilitu zariadenia.",
        "(No subfolders)": "(Žiadne podpriečinky)",
        "Archive: %s": "Archív: %s",
        "Are you sure you want to restore this backup?\n\nAn automatic safety rollback snapshot will be created before any files are updated.": "Naozaj chcete obnoviť túto zálohu?\n\nPred aktualizáciou súborov sa vytvorí automatický bezpečnostný bod obnovenia.",
        "Backup & Restore Settings": "Nastavenia zálohovania a obnovy",
        "Backup Folder:\n%s": "Priečinok záloh:\n%s",
        "Backup Name": "Názov zálohy",
        "Backup created successfully!\n\nFile: %s\nSize: %s\nArchived files: %d": "Záloha úspešne vytvorená!\n\nSúbor: %s\nVeľkosť: %s\nArchivované súbory: %d",
        "Backup received successfully!\n\nFile: %s": "Záloha úspešne prijatá!\n\nSúbor: %s",
        "Backup restored successfully!": "Záloha bola úspešne obnovená!",
        "Backup: Beam to Another Device": "Záloha: Odoslať cez Beam",
        "Backup: Create Backup": "Záloha: Vytvoriť zálohu",
        "Backup: Open Manager": "Záloha: Otvoriť správcu",
        "Backup: Receive via Beam Code": "Záloha: Prijať cez Beam kód",
        "Backup: Restore Backup": "Záloha: Obnoviť zálohu",
        "Beam Relay Server URL": "URL Beam relay servera",
        "Beam Relay Server:\n%s": "Beam server:\n%s",
        "Beam code expired or not found. Please verify the 6-digit code on the sending device.": "Platnosť Beam kódu vypršala alebo nebol nájdený. Skontrolujte 6-miestny kód na odosielajúcom zariadení.",
        "Beam code must be exactly %d digits.": "Beam kód musí mať presne %d číslic.",
        "Beam code ready!": "Beam kód je pripravený!",
        "Beam reception failed:\n%s": "Príjem Beam zlyhal:\n%s",
        "Beam to Another Device...": "Odoslať na iné zariadenie...",
        "Beam to Device": "Odoslať na zariadenie",
        "Beam to Device...": "Odoslať na zariadenie...",
        "Beam transfer canceled.": "Prenos Beam bol zrušený.",
        "Beam upload failed:\n%s": "Nahrávanie Beam zlyhalo:\n%s",
        "Browse Folder": "Prehľadávať priečinok",
        "Browse Other Folder...": "Prehľadávať iný priečinok...",
        "Cancel": "Zrušiť",
        "Cancel Transfer": "Zrušiť prenos",
        "Choose Backup Folder": "Vybrať priečinok záloh",
        "Clean Slate (Remove unlisted plugins)": "Čistá inštalácia (odstrániť neuvedené doplnky)",
        "Clear All": "Zrušiť výber",
        "Close": "Zavrieť",
        "Code expires in 15 minutes\nSingle-use end-to-end encrypted": "Kód vyprší o 15 minút\nJednorazové koncové šifrovanie",
        "Connecting and downloading backup archive...": "Pripájanie a sťahovanie archívu...",
        "Connecting to Beam relay and downloading backup...\nPlease wait.": "Pripájanie k Beam a sťahovanie zálohy...\nČakajte prosím.",
        "Connecting to Beam relay...": "Pripájanie k Beam serveru...",
        "Corrupted or empty Beam payload.": "Poškodené alebo prázdne Beam dáta.",
        "Could not read file: %s": "Súbor sa nepodarilo prečítať: %s",
        "Could not write file: %s": "Súbor sa nepodarilo zapísať: %s",
        "Create": "Vytvoriť",
        "Create Backup": "Vytvoriť zálohu",
        "Create Backup...": "Vytvoriť zálohu...",
        "Create subfolder in '%s':": "Vytvoriť podpriečinok v '%s':",
        "Create, manage, and restore modular KOReader backups with intelligent cross-device hardware sanitization and disaster recovery.": "Vytvárajte, spravujte a obnovujte modulárne zálohy KOReader s inteligentným prispôsobením hardvéru a obnovou po havárii.",
        "Creating backup archive...\nPlease wait.": "Vytvára sa archív zálohy...\nČakajte prosím.",
        "Default Format: .%s (Tap to toggle)": "Predvolený formát: .%s (ťuknutím zmeňte)",
        "Delete": "Odstrániť",
        "Delete Backup": "Odstrániť zálohu",
        "Delete backup '%s'?\nThis action cannot be undone.": "Odstrániť zálohu '%s'?\nTúto akciu nemožno vrátiť späť.",
        "Device Backup & Restore": "Zálohovanie a obnova zariadenia",
        "Dictionaries & OCR Data": "Slovníky a OCR dáta",
        "Done": "Hotovo",
        "Download failed (HTTP %s): %s": "Sťahovanie zlyhalo (HTTP %s): %s",
        "Encrypting backup and uploading to Beam relay...\nPlease wait.": "Šifrovanie zálohy a odosielanie na Beam...\nČakajte prosím.",
        "Encrypting backup archive...": "Šifruje sa archív zálohy...",
        "Enter custom filename (without extension):": "Zadajte vlastný názov súboru (bez prípony):",
        "Enter the 6-digit Beam code from the sending device:": "Zadajte 6-miestny Beam kód z odosielajúceho zariadenia:",
        "Extraction failed: %s": "Extrakcia zlyhala: %s",
        "Failed to create backup:\n%s": "Nepodarilo sa vytvoriť zálohu:\n%s",
        "Failed to create folder.": "Vytvorenie priečinka zlyhalo.",
        "Failed to inspect archive:\n": "Kontrola archívu zlyhala:\n",
        "Fonts": "Písma",
        "Format: .%s": "Formát: .%s",
        "HTTPS address of the ephemeral Beam relay:": "HTTPS adresa dočasného Beam servera:",
        "Invalid Beam archive format.": "Neplatný formát Beam archívu.",
        "Invalid Beam code or corrupted data.": "Neplatný Beam kód alebo poškodené dáta.",
        "Invalid filename in Beam payload.": "Neplatný názov súboru v Beam dátach.",
        "Manage Backups": "Spravovať zálohy",
        "Manage Backups...": "Spravovať zálohy...",
        "Name: %s": "Názov: %s",
        "New Folder": "Nový priečinok",
        "Next": "Ďalej",
        "No backup files found in:\n%s": "Nenašli sa žiadne záložné súbory v:\n%s",
        "No backup files found in:\n%s\n\nWould you like to browse a different folder?": "Nenašli sa žiadne zálohy v:\n%s\n\nChcete prehľadať iný priečinok?",
        "No backup files found in:\n%s\n\nWould you like to create a new backup now?": "Nenašli sa žiadne zálohy v:\n%s\n\nChcete teraz vytvoriť novú zálohu?",
        "No backup files found.": "Nenašli sa žiadne záložné súbory.",
        "No rollback snapshot available to undo.": "Nie je k dispozícii žiadny bod obnovenia.",
        "Number of rolling backups to keep (0 = unlimited):": "Počet uchovávaných záloh (0 = neobmedzene):",
        "OK": "OK",
        "On the receiving device, open\n'Receive via Beam Code' and enter:": "Na prijímajúcom zariadení otvorte\n'Prijať cez Beam kód' a zadajte:",
        "Patches": "Záplaty",
        "Please enter a 6-digit Beam code.": "Zadajte 6-miestny Beam kód.",
        "Pre-flight check failed: %s": "Predbežná kontrola zlyhala: %s",
        "Preparing and encrypting backup archive...": "Príprava a šifrovanie archívu zálohy...",
        "Previous": "Späť",
        "Reading History & Stats": "História čítania a štatistiky",
        "Reading Progress & Notes": "Postup čítania a poznámky",
        "Receive & Restore": "Prijať a obnoviť",
        "Receive via Beam Code": "Prijať cez Beam kód",
        "Receive via Beam Code...": "Prijať cez Beam kód...",
        "Recommended": "Odporúčané",
        "Registering code with Beam relay...": "Registrácia kódu na Beam serveri...",
        "Reset Default": "Obnoviť predvolené",
        "Restart KOReader now to apply all changes?": "Reštartovať KOReader pre uplatnenie zmien?",
        "Restart later": "Reštartovať neskôr",
        "Restart now": "Reštartovať teraz",
        "Restore Backup": "Obnoviť zálohu",
        "Restore Backup...": "Obnoviť zálohu...",
        "Restore Now": "Obnoviť teraz",
        "Restore completed.": "Obnova bola dokončená.",
        "Restore failed: ": "Obnova zlyhala: ",
        "Restore: %s": "Obnoviť: %s",
        "Restoring backup...\nPlease wait.": "Obnovuje sa záloha...\nČakajte prosím.",
        "Retention Limit": "Limit uchovávania",
        "Retention Limit: Keep newest %d backups": "Limit uchovávania: ponechať %d najnovších záloh",
        "Revert to the pre-restore rollback snapshot?\n\nThis will undo the last restore and return your settings and patches to their prior state.\n\nKOReader will restart immediately.": "Vrátiť sa k bodu obnovenia pred obnovou?\n\nTýmto zrušíte poslednú obnovu a vrátite nastavenia a záplaty do predchádzajúceho stavu.\n\nKOReader sa okamžite reštartuje.",
        "Reverting to rollback snapshot...": "Návrat k bodu obnovenia...",
        "Sanitize Hardware Settings": "Vyčistiť nastavenia hardvéru",
        "Save": "Uložiť",
        "Screensavers": "Šetriče obrazovky",
        "Select All": "Vybrať všetko",
        "Select Backup Folder": "Vybrať priečinok záloh",
        "Select Backup to Beam": "Vybrať zálohu na odoslanie",
        "Select Backup to Restore": "Vybrať zálohu na obnovenie",
        "Select This Folder": "Vybrať tento priečinok",
        "Set Name": "Nastaviť názov",
        "Settings & UI Gestures": "Nastavenia a gestá rozhrania",
        "Settings...": "Nastavenia...",
        "Source directory does not exist: %s": "Zdrojový adresár neexistuje: %s",
        "Style Tweaks": "Úpravy štýlu",
        "Successfully reverted to rollback snapshot.": "Úspešne vrátené k bodu obnovenia.",
        "Undo Last Restore": "Vrátiť poslednú obnovu",
        "Undo Restore": "Vrátiť obnovu",
        "Undo failed: ": "Vrátenie zlyhalo: ",
        "Upload failed (HTTP %s): %s": "Nahrávanie zlyhalo (HTTP %s): %s",
        "Uploading backup archive...": "Nahráva sa archív zálohy...",
        "User Plugins": "Používateľské pluginy",
        "[Up]  ..  (Parent folder)": "[Hore]  ..  (Nadradený priečinok)",
        "btn_cancel": "Zrušiť",
        "btn_close": "Zavrieť",
        "btn_create": "Vytvoriť",
        "btn_ok": "OK",
        "btn_restore": "Obnoviť",
        "btn_settings": "Nastavenia...",
        "plugin_desc": "Vytvárajte, spravujte a obnovujte modulárne zálohy KOReader s inteligentným prispôsobením hardvéru a obnovou po havárii.",
        "plugin_name": "Zálohovanie a obnova zariadenia"
    },
    'sr': {
        "\n\nSanitized %d hardware keys for device compatibility.": "\n\nПречишћено %d хардверских кључева ради компатибилности.",
        "(No subfolders)": "(Нема потфасцикли)",
        "Archive: %s": "Архива: %s",
        "Are you sure you want to restore this backup?\n\nAn automatic safety rollback snapshot will be created before any files are updated.": "Да ли сте сигурни да желите да вратите ову резервну копију?\n\nАутоматска безбедносна тачка враћања биће направљена пре измене датотека.",
        "Backup & Restore Settings": "Подешавања резервне копије и враћања",
        "Backup Folder:\n%s": "Фасцикла резервних копија:\n%s",
        "Backup Name": "Назив резервне копије",
        "Backup created successfully!\n\nFile: %s\nSize: %s\nArchived files: %d": "Резервна копија је успешно направљена!\n\nДатотека: %s\nВеличина: %s\nАрхивираних датотека: %d",
        "Backup received successfully!\n\nFile: %s": "Резервна копија је успешно примљена!\n\nДатотека: %s",
        "Backup restored successfully!": "Резервна копија је успешно враћена!",
        "Backup: Beam to Another Device": "Копија: Пошаљи на други уређај",
        "Backup: Create Backup": "Копија: Направи резервну копију",
        "Backup: Open Manager": "Копија: Отвори управљач",
        "Backup: Receive via Beam Code": "Копија: Прими преко Beam кода",
        "Backup: Restore Backup": "Копија: Врати резервну копију",
        "Beam Relay Server URL": "URL Beam релеј сервера",
        "Beam Relay Server:\n%s": "Beam сервер:\n%s",
        "Beam code expired or not found. Please verify the 6-digit code on the sending device.": "Beam код је истекао или није пронађен. Проверите 6-цифрени код на уређају који шаље.",
        "Beam code must be exactly %d digits.": "Beam код мора имати тачно %d цифара.",
        "Beam code ready!": "Beam код је спреман!",
        "Beam reception failed:\n%s": "Пријем преко Beam-а није успео:\n%s",
        "Beam to Another Device...": "Пошаљи на други уређај...",
        "Beam to Device": "Пошаљи на уређај",
        "Beam to Device...": "Пошаљи на уређај...",
        "Beam transfer canceled.": "Beam пренос је отказан.",
        "Beam upload failed:\n%s": "Beam отпремање није успело:\n%s",
        "Browse Folder": "Прегледај фасциклу",
        "Browse Other Folder...": "Прегледај другу фасциклу...",
        "Cancel": "Откажи",
        "Cancel Transfer": "Откажи пренос",
        "Choose Backup Folder": "Изабери фасциклу резервних копија",
        "Clean Slate (Remove unlisted plugins)": "Чиста инсталација (уклони ненаведене прикључке)",
        "Clear All": "Откажи све",
        "Close": "Затвори",
        "Code expires in 15 minutes\nSingle-use end-to-end encrypted": "Код истиче за 15 минута\nЈеднократна шифрована веза с краја на крај",
        "Connecting and downloading backup archive...": "Повезивање и преузимање архиве...",
        "Connecting to Beam relay and downloading backup...\nPlease wait.": "Повезивање на Beam сервер и преузимање...\nМолимо сачекајте.",
        "Connecting to Beam relay...": "Повезивање на Beam сервер...",
        "Corrupted or empty Beam payload.": "Оштећен или празан Beam садржај.",
        "Could not read file: %s": "Није могуће прочитати датотеку: %s",
        "Could not write file: %s": "Није могуће уписати датотеку: %s",
        "Create": "Направи",
        "Create Backup": "Направи резервну копију",
        "Create Backup...": "Направи резервну копију...",
        "Create subfolder in '%s':": "Направи потфасциклу у '%s':",
        "Create, manage, and restore modular KOReader backups with intelligent cross-device hardware sanitization and disaster recovery.": "Правите, управљајте и враћајте модуларне KOReader копије уз интелигентно прилагођавање хардверу и опоравак од хаварија.",
        "Creating backup archive...\nPlease wait.": "Прављење архиве резервне копије...\nМолимо сачекајте.",
        "Default Format: .%s (Tap to toggle)": "Подразумевани формат: .%s (додирните за измену)",
        "Delete": "Обриши",
        "Delete Backup": "Обриши копију",
        "Delete backup '%s'?\nThis action cannot be undone.": "Обрисати резервну копију '%s'?\nОва радња се не може опозвати.",
        "Device Backup & Restore": "Резервна копија и враћање уређаја",
        "Dictionaries & OCR Data": "Речници и OCR подаци",
        "Done": "Завршено",
        "Download failed (HTTP %s): %s": "Преузимање није успело (HTTP %s): %s",
        "Encrypting backup and uploading to Beam relay...\nPlease wait.": "Шифровање копије и отпремање на Beam...\nМолимо сачекајте.",
        "Encrypting backup archive...": "Шифровање архиве резервне копије...",
        "Enter custom filename (without extension):": "Унесите назив датотеке (без екстензије):",
        "Enter the 6-digit Beam code from the sending device:": "Унесите 6-цифрени Beam код са уређаја који шаље:",
        "Extraction failed: %s": "Распакивање није успело: %s",
        "Failed to create backup:\n%s": "Прављење копије није успело:\n%s",
        "Failed to create folder.": "Прављење фасцикле није успело.",
        "Failed to inspect archive:\n": "Провера архиве није успела:\n",
        "Fonts": "Фонтови",
        "Format: .%s": "Формат: .%s",
        "HTTPS address of the ephemeral Beam relay:": "HTTPS адреса привременог Beam сервера:",
        "Invalid Beam archive format.": "Неважећи формат Beam архиве.",
        "Invalid Beam code or corrupted data.": "Неважећи Beam код или оштећени подаци.",
        "Invalid filename in Beam payload.": "Неважећи назив датотеке у Beam подацима.",
        "Manage Backups": "Управљај копијама",
        "Manage Backups...": "Управљај копијама...",
        "Name: %s": "Назив: %s",
        "New Folder": "Нова фасцикла",
        "Next": "Следеће",
        "No backup files found in:\n%s": "Нису пронађене резервне копије у:\n%s",
        "No backup files found in:\n%s\n\nWould you like to browse a different folder?": "Нису пронађене копије у:\n%s\n\nЖелите ли да прегледате другу фасциклу?",
        "No backup files found in:\n%s\n\nWould you like to create a new backup now?": "Нису пронађене копије у:\n%s\n\nЖелите ли да направите нову копију сада?",
        "No backup files found.": "Нису пронађене резервне копије.",
        "No rollback snapshot available to undo.": "Нема доступне тачке враћања за опозив.",
        "Number of rolling backups to keep (0 = unlimited):": "Број ротирајућих копија које се чувају (0 = неограничено):",
        "OK": "У реду",
        "On the receiving device, open\n'Receive via Beam Code' and enter:": "На пријемном уређају отворите\n'Прими преко Beam кода' и унесите:",
        "Patches": "Закрпе",
        "Please enter a 6-digit Beam code.": "Молимо унесите 6-цифрени Beam код.",
        "Pre-flight check failed: %s": "Прелиминарна провера није успела: %s",
        "Preparing and encrypting backup archive...": "Припрема и шифровање архиве...",
        "Previous": "Претходно",
        "Reading History & Stats": "Историја читања и статистика",
        "Reading Progress & Notes": "Напредак читања и белешке",
        "Receive & Restore": "Прими и врати",
        "Receive via Beam Code": "Прими преко Beam кода",
        "Receive via Beam Code...": "Прими преко Beam кода...",
        "Recommended": "Препоручено",
        "Registering code with Beam relay...": "Регистрација кода на Beam серверу...",
        "Reset Default": "Врати подразумевано",
        "Restart KOReader now to apply all changes?": "Поново покренути KOReader ради примене измена?",
        "Restart later": "Касније",
        "Restart now": "Сада",
        "Restore Backup": "Врати резервну копију",
        "Restore Backup...": "Врати резервну копију...",
        "Restore Now": "Врати сада",
        "Restore completed.": "Враћање је завршено.",
        "Restore failed: ": "Враћање није успело: ",
        "Restore: %s": "Врати: %s",
        "Restoring backup...\nPlease wait.": "Враћање резервне копије...\nМолимо сачекајте.",
        "Retention Limit": "Ограничење чувања",
        "Retention Limit: Keep newest %d backups": "Ограничење: задржи %d најновијих копија",
        "Revert to the pre-restore rollback snapshot?\n\nThis will undo the last restore and return your settings and patches to their prior state.\n\nKOReader will restart immediately.": "Вратити се на стање пре последњег враћања?\n\nОво ће опозвати последње враћање и вратити подешавања и закрпе на претходно стање.\n\nKOReader ће се одмах поново покренути.",
        "Reverting to rollback snapshot...": "Враћање на претходну тачку...",
        "Sanitize Hardware Settings": "Прилагоди хардверска подешавања",
        "Save": "Сачувај",
        "Screensavers": "Чувари екрана",
        "Select All": "Изабери све",
        "Select Backup Folder": "Изабери фасциклу копија",
        "Select Backup to Beam": "Изабери копију за слање",
        "Select Backup to Restore": "Изабери копију за враћање",
        "Select This Folder": "Изабери ову фасциклу",
        "Set Name": "Постави назив",
        "Settings & UI Gestures": "Подешавања и покрети",
        "Settings...": "Подешавања...",
        "Source directory does not exist: %s": "Изворни директоријум не постоји: %s",
        "Style Tweaks": "Подешавања стила",
        "Successfully reverted to rollback snapshot.": "Успешно враћено на безбедносну тачку.",
        "Undo Last Restore": "Опозови последње враћање",
        "Undo Restore": "Опозови враћање",
        "Undo failed: ": "Опозив није успео: ",
        "Upload failed (HTTP %s): %s": "Отпремање није успело (HTTP %s): %s",
        "Uploading backup archive...": "Отпремање архиве копије...",
        "User Plugins": "Кориснички прикључци",
        "[Up]  ..  (Parent folder)": "[Горе]  ..  (Надређена фасцикла)",
        "btn_cancel": "Откажи",
        "btn_close": "Затвори",
        "btn_create": "Направи",
        "btn_ok": "У реду",
        "btn_restore": "Врати",
        "btn_settings": "Подешавања...",
        "plugin_desc": "Правите, управљајте и враћајте модуларне KOReader копије уз интелигентно прилагођавање хардверу и опоравак од хаварија.",
        "plugin_name": "Резервна копија и враћање уређаја"
    },
    'ar': {
        "\n\nSanitized %d hardware keys for device compatibility.": "\n\nتم تنظيف %d مفتاحاً للأجهزة لضمان التوافق.",
        "(No subfolders)": "(لا توجد مجلدات فرعية)",
        "Archive: %s": "الأرشيف: %s",
        "Are you sure you want to restore this backup?\n\nAn automatic safety rollback snapshot will be created before any files are updated.": "هل أنت متأكد من استعادة هذه النسخة الاحتياطية؟\n\nسيتم إنشاء نقطة استعادة أمان تلقائية قبل تحديث أي ملفات.",
        "Backup & Restore Settings": "إعدادات النسخ الاحتياطي والاستعادة",
        "Backup Folder:\n%s": "مجلد النسخ الاحتياطي:\n%s",
        "Backup Name": "اسم النسخة",
        "Backup created successfully!\n\nFile: %s\nSize: %s\nArchived files: %d": "تم إنشاء النسخة الاحتياطية بنجاح!\n\nالملف: %s\nالحجم: %s\nالملفات المؤرشفة: %d",
        "Backup received successfully!\n\nFile: %s": "تم استلام النسخة الاحتياطية بنجاح!\n\nالملف: %s",
        "Backup restored successfully!": "تمت استعادة النسخة الاحتياطية بنجاح!",
        "Backup: Beam to Another Device": "النسخ: إرسال عبر Beam لجهاز آخر",
        "Backup: Create Backup": "النسخ: إنشاء نسخة احتياطية",
        "Backup: Open Manager": "النسخ: فتح إدارة النسخ",
        "Backup: Receive via Beam Code": "النسخ: استلام برمز Beam",
        "Backup: Restore Backup": "النسخ: استعادة نسخة احتياطية",
        "Beam Relay Server URL": "رابط خادم ترحيل Beam",
        "Beam Relay Server:\n%s": "خادم ترحيل Beam:\n%s",
        "Beam code expired or not found. Please verify the 6-digit code on the sending device.": "رمز Beam منتهي الصلاحية أو غير موجود. يرجى التحقق من الرمز المكون من 6 أرقام على الجهاز المرسل.",
        "Beam code must be exactly %d digits.": "يجب أن يتكون رمز Beam من %d أرقام بالضبط.",
        "Beam code ready!": "رمز Beam جاهز!",
        "Beam reception failed:\n%s": "فشل استلام Beam:\n%s",
        "Beam to Another Device...": "إرسال عبر Beam لجهاز آخر...",
        "Beam to Device": "إرسال عبر Beam للجهاز",
        "Beam to Device...": "إرسال عبر Beam للجهاز...",
        "Beam transfer canceled.": "تم إلغاء نقل Beam.",
        "Beam upload failed:\n%s": "فشل رفع Beam:\n%s",
        "Browse Folder": "استعراض المجلد",
        "Browse Other Folder...": "استعراض مجلد آخر...",
        "Cancel": "إلغاء",
        "Cancel Transfer": "إلغاء النقل",
        "Choose Backup Folder": "اختيار مجلد النسخ",
        "Clean Slate (Remove unlisted plugins)": "تثبيت نظيف (إزالة الإضافات غير المدرجة)",
        "Clear All": "إلغاء تحديد الكل",
        "Close": "إغلاق",
        "Code expires in 15 minutes\nSingle-use end-to-end encrypted": "ينتهي الرمز خلال 15 دقيقة\nمشفر من طرف لطرف للاستخدام مرة واحدة",
        "Connecting and downloading backup archive...": "جارٍ الاتصال وتنزيل أرشيف النسخة...",
        "Connecting to Beam relay and downloading backup...\nPlease wait.": "جارٍ الاتصال بخادم Beam وتنزيل النسخة...\nيرجى الانتظار.",
        "Connecting to Beam relay...": "جارٍ الاتصال بخادم Beam...",
        "Corrupted or empty Beam payload.": "بيانات Beam تالفة أو فارغة.",
        "Could not read file: %s": "تعذر قراءة الملف: %s",
        "Could not write file: %s": "تعذر كتابة الملف: %s",
        "Create": "إنشاء",
        "Create Backup": "إنشاء نسخة احتياطية",
        "Create Backup...": "إنشاء نسخة احتياطية...",
        "Create subfolder in '%s':": "إنشاء مجلد فرعي في '%s':",
        "Create, manage, and restore modular KOReader backups with intelligent cross-device hardware sanitization and disaster recovery.": "إنشاء وإدارة واستعادة نسخ احتياطية معيارية لـ KOReader مع ضبط توافق الأجهزة والتعافي من الكوارث.",
        "Creating backup archive...\nPlease wait.": "جارٍ إنشاء أرشيف النسخة الاحتياطية...\nيرجى الانتظار.",
        "Default Format: .%s (Tap to toggle)": "التنسيق الافتراضي: .%s (المس للتبديل)",
        "Delete": "حذف",
        "Delete Backup": "حذف النسخة",
        "Delete backup '%s'?\nThis action cannot be undone.": "هل تريد حذف النسخة '%s'؟\nلا يمكن التراجع عن هذا الإجراء.",
        "Device Backup & Restore": "نسخ احتياطي واستعادة للجهاز",
        "Dictionaries & OCR Data": "القواميس وبيانات OCR",
        "Done": "تم",
        "Download failed (HTTP %s): %s": "فشل التنزيل (HTTP %s): %s",
        "Encrypting backup and uploading to Beam relay...\nPlease wait.": "تشفير النسخة ورفعها إلى Beam...\nيرجى الانتظار.",
        "Encrypting backup archive...": "جارٍ تشفير أرشيف النسخة...",
        "Enter custom filename (without extension):": "أدخل اسم الملف (بدون امتداد):",
        "Enter the 6-digit Beam code from the sending device:": "أدخل رمز Beam المكون من 6 أرقام من الجهاز المرسل:",
        "Extraction failed: %s": "فشل الاستخراج: %s",
        "Failed to create backup:\n%s": "فشل إنشاء النسخة الاحتياطية:\n%s",
        "Failed to create folder.": "فشل إنشاء المجلد.",
        "Failed to inspect archive:\n": "فشل فحص الأرشيف:\n",
        "Fonts": "الخطوط",
        "Format: .%s": "التنسيق: .%s",
        "HTTPS address of the ephemeral Beam relay:": "عنوان HTTPS لخادم ترحيل Beam المؤقت:",
        "Invalid Beam archive format.": "تنسيق أرشيف Beam غير صالح.",
        "Invalid Beam code or corrupted data.": "رمز Beam غير صالح أو بيانات تالفة.",
        "Invalid filename in Beam payload.": "اسم ملف غير صالح في بيانات Beam.",
        "Manage Backups": "إدارة النسخ",
        "Manage Backups...": "إدارة النسخ...",
        "Name: %s": "الاسم: %s",
        "New Folder": "مجلد جديد",
        "Next": "التالي",
        "No backup files found in:\n%s": "لم يتم العثور على ملفات نسخ في:\n%s",
        "No backup files found in:\n%s\n\nWould you like to browse a different folder?": "لم يتم العثور على نسخ في:\n%s\n\nهل ترغب في استعراض مجلد آخر؟",
        "No backup files found in:\n%s\n\nWould you like to create a new backup now?": "لم يتم العثور على نسخ في:\n%s\n\nهل ترغب في إنشاء نسخة جديدة الآن؟",
        "No backup files found.": "لم يتم العثور على نسخ احتياطية.",
        "No rollback snapshot available to undo.": "لا تتوفر نقطة استعادة للتراجع.",
        "Number of rolling backups to keep (0 = unlimited):": "عدد النسخ الاحتياطية المحتفظ بها (0 = غير محدود):",
        "OK": "حسناً",
        "On the receiving device, open\n'Receive via Beam Code' and enter:": "على الجهاز المستقبل، افتح\n'استلام برمز Beam' وأدخل:",
        "Patches": "الترقيعات",
        "Please enter a 6-digit Beam code.": "يرجى إدخال رمز Beam المكون من 6 أرقام.",
        "Pre-flight check failed: %s": "فشل الفحص المسبق: %s",
        "Preparing and encrypting backup archive...": "تحضير وتشفير أرشيف النسخة...",
        "Previous": "السابق",
        "Reading History & Stats": "تاريخ القراءة والإحصائيات",
        "Reading Progress & Notes": "تقدم القراءة والملاحظات",
        "Receive & Restore": "استلام واستعادة",
        "Receive via Beam Code": "استلام برمز Beam",
        "Receive via Beam Code...": "استلام برمز Beam...",
        "Recommended": "موصى به",
        "Registering code with Beam relay...": "تسجيل الرمز في خادم Beam...",
        "Reset Default": "استعادة الافتراضي",
        "Restart KOReader now to apply all changes?": "إعادة تشغيل KOReader لتطبيق التغييرات؟",
        "Restart later": "إعادة التشغيل لاحقاً",
        "Restart now": "إعادة التشغيل الآن",
        "Restore Backup": "استعادة نسخة",
        "Restore Backup...": "استعادة نسخة...",
        "Restore Now": "استعادة الآن",
        "Restore completed.": "اكتملت الاستعادة.",
        "Restore failed: ": "فشلت الاستعادة: ",
        "Restore: %s": "استعادة: %s",
        "Restoring backup...\nPlease wait.": "جارٍ استعادة النسخة الاحتياطية...\nيرجى الانتظار.",
        "Retention Limit": "حد الاحتفاظ",
        "Retention Limit: Keep newest %d backups": "حد الاحتفاظ: الاحتفاظ بأحدث %d نسخ",
        "Revert to the pre-restore rollback snapshot?\n\nThis will undo the last restore and return your settings and patches to their prior state.\n\nKOReader will restart immediately.": "الرجوع إلى نقطة ما قبل الاستعادة؟\n\nسيؤدي هذا إلى التراجع عن آخر استعادة وإعادة إعداداتك إلى حالتها السابقة.\n\nسيتم إعادة تشغيل KOReader فوراً.",
        "Reverting to rollback snapshot...": "جارٍ الرجوع إلى نقطة الأمان...",
        "Sanitize Hardware Settings": "تنظيف إعدادات الأجهزة",
        "Save": "حفظ",
        "Screensavers": "شاشات التوقف",
        "Select All": "تحديد الكل",
        "Select Backup Folder": "اختيار مجلد النسخ",
        "Select Backup to Beam": "اختيار نسخة للإرسال",
        "Select Backup to Restore": "اختيار نسخة للاستعادة",
        "Select This Folder": "اختيار هذا المجلد",
        "Set Name": "تعيين الاسم",
        "Settings & UI Gestures": "الإعدادات وإيماءات الواجهة",
        "Settings...": "الإعدادات...",
        "Source directory does not exist: %s": "المجلد المصدر غير موجود: %s",
        "Style Tweaks": "تعديلات النمط",
        "Successfully reverted to rollback snapshot.": "تم الرجوع بنجاح إلى نقطة الاستعادة.",
        "Undo Last Restore": "التراجع عن آخر استعادة",
        "Undo Restore": "التراجع عن الاستعادة",
        "Undo failed: ": "فشل التراجع: ",
        "Upload failed (HTTP %s): %s": "فشل الرفع (HTTP %s): %s",
        "Uploading backup archive...": "جارٍ رفع أرشيف النسخة...",
        "User Plugins": "إضافات المستخدم",
        "[Up]  ..  (Parent folder)": "[أعلى]  ..  (المجلد الأصلي)",
        "btn_cancel": "إلغاء",
        "btn_close": "إغلاق",
        "btn_create": "إنشاء",
        "btn_ok": "حسناً",
        "btn_restore": "استعادة",
        "btn_settings": "الإعدادات...",
        "plugin_desc": "إنشاء وإدارة واستعادة نسخ احتياطية معيارية لـ KOReader مع ضبط توافق الأجهزة والتعافي من الكوارث.",
        "plugin_name": "نسخ احتياطي واستعادة للجهاز"
    },
    'id': {
        "\n\nSanitized %d hardware keys for device compatibility.": "\n\nMembersihkan %d kunci perangkat keras untuk kompatibilitas perangkat.",
        "(No subfolders)": "(Tidak ada subfolder)",
        "Archive: %s": "Arsip: %s",
        "Are you sure you want to restore this backup?\n\nAn automatic safety rollback snapshot will be created before any files are updated.": "Apakah Anda yakin ingin memulihkan cadangan ini?\n\nTitik pemulihan aman otomatis akan dibuat sebelum file diperbarui.",
        "Backup & Restore Settings": "Pengaturan Cadangan & Pemulihan",
        "Backup Folder:\n%s": "Folder Cadangan:\n%s",
        "Backup Name": "Nama Cadangan",
        "Backup created successfully!\n\nFile: %s\nSize: %s\nArchived files: %d": "Cadangan berhasil dibuat!\n\nFile: %s\nUkuran: %s\nFile diarsipkan: %d",
        "Backup received successfully!\n\nFile: %s": "Cadangan berhasil diterima!\n\nFile: %s",
        "Backup restored successfully!": "Cadangan berhasil dipulihkan!",
        "Backup: Beam to Another Device": "Cadangan: Pancarkan ke Perangkat Lain",
        "Backup: Create Backup": "Cadangan: Buat Cadangan",
        "Backup: Open Manager": "Cadangan: Buka Pengelola",
        "Backup: Receive via Beam Code": "Cadangan: Terima via Kode Beam",
        "Backup: Restore Backup": "Cadangan: Pulihkan Cadangan",
        "Beam Relay Server URL": "URL Server Relai Beam",
        "Beam Relay Server:\n%s": "Server Relai Beam:\n%s",
        "Beam code expired or not found. Please verify the 6-digit code on the sending device.": "Kode Beam kedaluwarsa atau tidak ditemukan. Harap verifikasi kode 6 digit pada perangkat pengirim.",
        "Beam code must be exactly %d digits.": "Kode Beam harus tepat %d digit.",
        "Beam code ready!": "Kode Beam siap!",
        "Beam reception failed:\n%s": "Penerimaan Beam gagal:\n%s",
        "Beam to Another Device...": "Pancarkan ke Perangkat Lain...",
        "Beam to Device": "Pancarkan ke Perangkat",
        "Beam to Device...": "Pancarkan ke Perangkat...",
        "Beam transfer canceled.": "Transfer Beam dibatalkan.",
        "Beam upload failed:\n%s": "Unggah Beam gagal:\n%s",
        "Browse Folder": "Jelajahi Folder",
        "Browse Other Folder...": "Jelajahi Folder Lain...",
        "Cancel": "Batal",
        "Cancel Transfer": "Batalkan Transfer",
        "Choose Backup Folder": "Pilih Folder Cadangan",
        "Clean Slate (Remove unlisted plugins)": "Instalasi Bersih (hapus plugin yang tidak terdaftar)",
        "Clear All": "Hapus Semua",
        "Close": "Tutup",
        "Code expires in 15 minutes\nSingle-use end-to-end encrypted": "Kode kedaluwarsa dalam 15 menit\nTerenkripsi ujung-ke-ujung (sekali pakai)",
        "Connecting and downloading backup archive...": "Menghubungkan dan mengunduh arsip cadangan...",
        "Connecting to Beam relay and downloading backup...\nPlease wait.": "Menghubungkan ke relai Beam dan mengunduh...\nHarap tunggu.",
        "Connecting to Beam relay...": "Menghubungkan ke relai Beam...",
        "Corrupted or empty Beam payload.": "Muatan Beam rusak atau kosong.",
        "Could not read file: %s": "Tidak dapat membaca file: %s",
        "Could not write file: %s": "Tidak dapat menulis file: %s",
        "Create": "Buat",
        "Create Backup": "Buat Cadangan",
        "Create Backup...": "Buat Cadangan...",
        "Create subfolder in '%s':": "Buat subfolder di '%s':",
        "Create, manage, and restore modular KOReader backups with intelligent cross-device hardware sanitization and disaster recovery.": "Buat, kelola, dan pulihkan cadangan modular KOReader dengan penyesuaian perangkat keras dan pemulihan bencana.",
        "Creating backup archive...\nPlease wait.": "Membuat arsip cadangan...\nHarap tunggu.",
        "Default Format: .%s (Tap to toggle)": "Format Default: .%s (Ketuk untuk ganti)",
        "Delete": "Hapus",
        "Delete Backup": "Hapus Cadangan",
        "Delete backup '%s'?\nThis action cannot be undone.": "Hapus cadangan '%s'?\nTindakan ini tidak dapat diurungkan.",
        "Device Backup & Restore": "Cadangan & Pemulihan Perangkat",
        "Dictionaries & OCR Data": "Kamus & Data OCR",
        "Done": "Selesai",
        "Download failed (HTTP %s): %s": "Unduhan gagal (HTTP %s): %s",
        "Encrypting backup and uploading to Beam relay...\nPlease wait.": "Mengenkripsi dan mengunggah ke relai Beam...\nHarap tunggu.",
        "Encrypting backup archive...": "Mengenkripsi arsip cadangan...",
        "Enter custom filename (without extension):": "Masukkan nama file (tanpa ekstensi):",
        "Enter the 6-digit Beam code from the sending device:": "Masukkan kode Beam 6 digit dari perangkat pengirim:",
        "Extraction failed: %s": "Ekstraksi gagal: %s",
        "Failed to create backup:\n%s": "Gagal membuat cadangan:\n%s",
        "Failed to create folder.": "Gagal membuat folder.",
        "Failed to inspect archive:\n": "Gagal memeriksa arsip:\n",
        "Fonts": "Font",
        "Format: .%s": "Format: .%s",
        "HTTPS address of the ephemeral Beam relay:": "Alamat HTTPS dari server relai sementara Beam:",
        "Invalid Beam archive format.": "Format arsip Beam tidak valid.",
        "Invalid Beam code or corrupted data.": "Kode Beam tidak valid atau data rusak.",
        "Invalid filename in Beam payload.": "Nama file tidak valid dalam muatan Beam.",
        "Manage Backups": "Kelola Cadangan",
        "Manage Backups...": "Kelola Cadangan...",
        "Name: %s": "Nama: %s",
        "New Folder": "Folder Baru",
        "Next": "Berikutnya",
        "No backup files found in:\n%s": "Tidak ada file cadangan ditemukan di:\n%s",
        "No backup files found in:\n%s\n\nWould you like to browse a different folder?": "Tidak ada cadangan ditemukan di:\n%s\n\nApakah Anda ingin mencari di folder lain?",
        "No backup files found in:\n%s\n\nWould you like to create a new backup now?": "Tidak ada cadangan ditemukan di:\n%s\n\nApakah Anda ingin membuat cadangan sekarang?",
        "No backup files found.": "Tidak ada file cadangan ditemukan.",
        "No rollback snapshot available to undo.": "Tidak ada titik pemulihan tersedia untuk dibatalkan.",
        "Number of rolling backups to keep (0 = unlimited):": "Jumlah cadangan berputar yang disimpan (0 = tanpa batas):",
        "OK": "OK",
        "On the receiving device, open\n'Receive via Beam Code' and enter:": "Pada perangkat penerima, buka\n'Terima via Kode Beam' dan masukkan:",
        "Patches": "Tambalan",
        "Please enter a 6-digit Beam code.": "Harap masukkan 6 digit kode Beam.",
        "Pre-flight check failed: %s": "Pemeriksaan awal gagal: %s",
        "Preparing and encrypting backup archive...": "Menyiapkan dan mengenkripsi arsip cadangan...",
        "Previous": "Sebelumnya",
        "Reading History & Stats": "Riwayat Membaca & Statistik",
        "Reading Progress & Notes": "Kemajuan Membaca & Catatan",
        "Receive & Restore": "Terima & Pulihkan",
        "Receive via Beam Code": "Terima via Kode Beam",
        "Receive via Beam Code...": "Terima via Kode Beam...",
        "Recommended": "Direkomendasikan",
        "Registering code with Beam relay...": "Mendaftarkan kode ke relai Beam...",
        "Reset Default": "Atur Ulang Default",
        "Restart KOReader now to apply all changes?": "Mulai ulang KOReader sekarang untuk menerapkan perubahan?",
        "Restart later": "Nanti",
        "Restart now": "Sekarang",
        "Restore Backup": "Pulihkan Cadangan",
        "Restore Backup...": "Pulihkan Cadangan...",
        "Restore Now": "Pulihkan Sekarang",
        "Restore completed.": "Pemulihan selesai.",
        "Restore failed: ": "Pemulihan gagal: ",
        "Restore: %s": "Pulihkan: %s",
        "Restoring backup...\nPlease wait.": "Memulihkan cadangan...\nHarap tunggu.",
        "Retention Limit": "Batas Retensi",
        "Retention Limit: Keep newest %d backups": "Batas retensi: Simpan %d cadangan terbaru",
        "Revert to the pre-restore rollback snapshot?\n\nThis will undo the last restore and return your settings and patches to their prior state.\n\nKOReader will restart immediately.": "Kembali ke titik pemulihan sebelum pemulihan?\n\nIni akan membatalkan pemulihan terakhir dan mengembalikan pengaturan Anda.\n\nKOReader akan segera dimulai ulang.",
        "Reverting to rollback snapshot...": "Kembali ke titik pemulihan...",
        "Sanitize Hardware Settings": "Bersihkan Pengaturan Perangkat Keras",
        "Save": "Simpan",
        "Screensavers": "Screensaver",
        "Select All": "Pilih Semua",
        "Select Backup Folder": "Pilih Folder Cadangan",
        "Select Backup to Beam": "Pilih Cadangan untuk Dipancarkan",
        "Select Backup to Restore": "Pilih Cadangan untuk Dipulihkan",
        "Select This Folder": "Pilih Folder Ini",
        "Set Name": "Tetapkan Nama",
        "Settings & UI Gestures": "Pengaturan & Gestur Antarmuka",
        "Settings...": "Pengaturan...",
        "Source directory does not exist: %s": "Direktori sumber tidak ada: %s",
        "Style Tweaks": "Penyesuaian Gaya",
        "Successfully reverted to rollback snapshot.": "Berhasil kembali ke titik pemulihan.",
        "Undo Last Restore": "Batalkan Pemulihan Terakhir",
        "Undo Restore": "Batalkan Pemulihan",
        "Undo failed: ": "Gagal membatalkan: ",
        "Upload failed (HTTP %s): %s": "Unggahan gagal (HTTP %s): %s",
        "Uploading backup archive...": "Mengunggah arsip cadangan...",
        "User Plugins": "Plugin Pengguna",
        "[Up]  ..  (Parent folder)": "[Naik]  ..  (Folder induk)",
        "btn_cancel": "Batal",
        "btn_close": "Tutup",
        "btn_create": "Buat",
        "btn_ok": "OK",
        "btn_restore": "Pulihkan",
        "btn_settings": "Pengaturan...",
        "plugin_desc": "Buat, kelola, dan pulihkan cadangan modular KOReader dengan penyesuaian perangkat keras dan pemulihan bencana.",
        "plugin_name": "Cadangan & Pemulihan Perangkat"
    }
}
