# Translations for Group 2: nl, pl, ru, uk, ja, ko

DATA = {
    'nl': {
        "\n\nSanitized %d hardware keys for device compatibility.": "\n\n%d hardwaresleutels geschoond voor apparaatcompatibiliteit.",
        "(No subfolders)": "(Geen submappen)",
        "Archive: %s": "Archief: %s",
        "Are you sure you want to restore this backup?\n\nAn automatic safety rollback snapshot will be created before any files are updated.": "Weet u zeker dat u deze back-up wilt herstellen?\n\nEr wordt automatisch een herstelpunt gemaakt voordat bestanden worden bijgewerkt.",
        "Backup & Restore Settings": "Back-up- en herstelinstellingen",
        "Backup Folder:\n%s": "Back-upmap:\n%s",
        "Backup Name": "Back-upnaam",
        "Backup created successfully!\n\nFile: %s\nSize: %s\nArchived files: %d": "Back-up succesvol aangemaakt!\n\nBestand: %s\nGrootte: %s\nGearchiveerde bestanden: %d",
        "Backup received successfully!\n\nFile: %s": "Back-up succesvol ontvangen!\n\nBestand: %s",
        "Backup restored successfully!": "Back-up succesvol hersteld!",
        "Backup: Beam to Another Device": "Back-up: Verzenden naar ander apparaat",
        "Backup: Create Backup": "Back-up: Back-up maken",
        "Backup: Open Manager": "Back-up: Beheer openen",
        "Backup: Receive via Beam Code": "Back-up: Ontvangen via Beam-code",
        "Backup: Restore Backup": "Back-up: Back-up herstellen",
        "Beam Relay Server URL": "Beam-relayserver-URL",
        "Beam Relay Server:\n%s": "Beam-relayserver:\n%s",
        "Beam code expired or not found. Please verify the 6-digit code on the sending device.": "Beam-code verlopen of niet gevonden. Controleer de 6-cijferige code op het verzendende apparaat.",
        "Beam code must be exactly %d digits.": "Beam-code moet precies %d cijfers bevatten.",
        "Beam code ready!": "Beam-code gereed!",
        "Beam reception failed:\n%s": "Beam-ontvangst mislukt:\n%s",
        "Beam to Another Device...": "Verzenden naar ander apparaat...",
        "Beam to Device": "Verzenden naar apparaat",
        "Beam to Device...": "Verzenden naar apparaat...",
        "Beam transfer canceled.": "Beam-overdracht geannuleerd.",
        "Beam upload failed:\n%s": "Beam-upload mislukt:\n%s",
        "Browse Folder": "Map bladeren",
        "Browse Other Folder...": "Andere map bladeren...",
        "Cancel": "Annuleren",
        "Cancel Transfer": "Overdracht annuleren",
        "Choose Backup Folder": "Back-upmap kiezen",
        "Clean Slate (Remove unlisted plugins)": "Schone installatie (niet-vermelde plug-ins verwijderen)",
        "Clear All": "Alles wissen",
        "Close": "Sluiten",
        "Code expires in 15 minutes\nSingle-use end-to-end encrypted": "Code verloopt over 15 minuten\nEenmalig gebruik, end-to-end versleuteld",
        "Connecting and downloading backup archive...": "Verbinden en back-up downloaden...",
        "Connecting to Beam relay and downloading backup...\nPlease wait.": "Verbinden met Beam-relay en back-up downloaden...\nEven geduld a.u.b.",
        "Connecting to Beam relay...": "Verbinden met Beam-relay...",
        "Corrupted or empty Beam payload.": "Beschadigde of lege Beam-gegevens.",
        "Could not read file: %s": "Kan bestand niet lezen: %s",
        "Could not write file: %s": "Kan bestand niet schrijven: %s",
        "Create": "Aanmaken",
        "Create Backup": "Back-up maken",
        "Create Backup...": "Back-up maken...",
        "Create subfolder in '%s':": "Submap aanmaken in '%s':",
        "Create, manage, and restore modular KOReader backups with intelligent cross-device hardware sanitization and disaster recovery.": "Maak, beheer en herstel modulaire KOReader-back-ups met intelligente hardwarecompatibiliteit en noodherstel.",
        "Creating backup archive...\nPlease wait.": "Back-uparchief aanmaken...\nEven geduld a.u.b.",
        "Default Format: .%s (Tap to toggle)": "Standaardformaat: .%s (tik om te wisselen)",
        "Delete": "Verwijderen",
        "Delete Backup": "Back-up verwijderen",
        "Delete backup '%s'?\nThis action cannot be undone.": "Back-up '%s' verwijderen?\nDit kan niet ongedaan worden gemaakt.",
        "Device Backup & Restore": "Apparaatback-up & Herstel",
        "Dictionaries & OCR Data": "Woordenboeken & OCR-gegevens",
        "Done": "Gereed",
        "Download failed (HTTP %s): %s": "Downloaden mislukt (HTTP %s): %s",
        "Encrypting backup and uploading to Beam relay...\nPlease wait.": "Versleutelen en uploaden naar Beam-relay...\nEven geduld a.u.b.",
        "Encrypting backup archive...": "Back-uparchief versleutelen...",
        "Enter custom filename (without extension):": "Voer bestandsnaam in (zonder extensie):",
        "Enter the 6-digit Beam code from the sending device:": "Voer de 6-cijferige Beam-code van het verzendende apparaat in:",
        "Extraction failed: %s": "Uitpakken mislukt: %s",
        "Failed to create backup:\n%s": "Aanmaken van back-up mislukt:\n%s",
        "Failed to create folder.": "Map aanmaken mislukt.",
        "Failed to inspect archive:\n": "Inspectie van archief mislukt:\n",
        "Fonts": "Lettertypen",
        "Format: .%s": "Formaat: .%s",
        "HTTPS address of the ephemeral Beam relay:": "HTTPS-adres van de tijdelijke Beam-relay:",
        "Invalid Beam archive format.": "Ongeldig Beam-archiefformaat.",
        "Invalid Beam code or corrupted data.": "Ongeldige Beam-code of beschadigde gegevens.",
        "Invalid filename in Beam payload.": "Ongeldige bestandsnaam in Beam-gegevens.",
        "Manage Backups": "Back-ups beheren",
        "Manage Backups...": "Back-ups beheren...",
        "Name: %s": "Naam: %s",
        "New Folder": "Nieuwe map",
        "Next": "Volgende",
        "No backup files found in:\n%s": "Geen back-upbestanden gevonden in:\n%s",
        "No backup files found in:\n%s\n\nWould you like to browse a different folder?": "Geen back-ups gevonden in:\n%s\n\nWilt u een andere map kiezen?",
        "No backup files found in:\n%s\n\nWould you like to create a new backup now?": "Geen back-ups gevonden in:\n%s\n\nWilt u nu een back-up maken?",
        "No backup files found.": "Geen back-upbestanden gevonden.",
        "No rollback snapshot available to undo.": "Geen herstelpunt beschikbaar om ongedaan te maken.",
        "Number of rolling backups to keep (0 = unlimited):": "Aantal te bewaren back-ups (0 = onbeperkt):",
        "OK": "OK",
        "On the receiving device, open\n'Receive via Beam Code' and enter:": "Open op het ontvangende apparaat\n'Ontvangen via Beam-code' en voer in:",
        "Patches": "Patches",
        "Please enter a 6-digit Beam code.": "Voer een 6-cijferige Beam-code in.",
        "Pre-flight check failed: %s": "Voorafgaande controle mislukt: %s",
        "Preparing and encrypting backup archive...": "Back-up voorbereiden en versleutelen...",
        "Previous": "Vorige",
        "Reading History & Stats": "Leesgeschiedenis & statistieken",
        "Reading Progress & Notes": "Leesvoortgang & notities",
        "Receive & Restore": "Ontvangen & herstellen",
        "Receive via Beam Code": "Ontvangen via Beam-code",
        "Receive via Beam Code...": "Ontvangen via Beam-code...",
        "Recommended": "Aanbevolen",
        "Registering code with Beam relay...": "Code registreren bij Beam-relay...",
        "Reset Default": "Standaard herstellen",
        "Restart KOReader now to apply all changes?": "KOReader nu herstarten om wijzigingen toe te passen?",
        "Restart later": "Later herstarten",
        "Restart now": "Nu herstarten",
        "Restore Backup": "Back-up herstellen",
        "Restore Backup...": "Back-up herstellen...",
        "Restore Now": "Nu herstellen",
        "Restore completed.": "Herstel voltooid.",
        "Restore failed: ": "Herstel mislukt: ",
        "Restore: %s": "Herstellen: %s",
        "Restoring backup...\nPlease wait.": "Back-up herstellen...\nEven geduld a.u.b.",
        "Retention Limit": "Bewaarlimiet",
        "Retention Limit: Keep newest %d backups": "Bewaarlimiet: nieuwste %d back-ups bewaren",
        "Revert to the pre-restore rollback snapshot?\n\nThis will undo the last restore and return your settings and patches to their prior state.\n\nKOReader will restart immediately.": "Terugkeren naar het eerdere herstelpunt?\n\nDit maakt het laatste herstel ongedaan en zet instellingen en patches terug.\n\nKOReader herstart direct.",
        "Reverting to rollback snapshot...": "Terugzetten naar herstelpunt...",
        "Sanitize Hardware Settings": "Hardware-instellingen schonen",
        "Save": "Opslaan",
        "Screensavers": "Schermbeveiligingen",
        "Select All": "Alles selecteren",
        "Select Backup Folder": "Back-upmap selecteren",
        "Select Backup to Beam": "Back-up kiezen om te zenden",
        "Select Backup to Restore": "Back-up kiezen om te herstellen",
        "Select This Folder": "Deze map selecteren",
        "Set Name": "Naam instellen",
        "Settings & UI Gestures": "Instellingen & schermgebaren",
        "Settings...": "Instellingen...",
        "Source directory does not exist: %s": "Bronmap bestaat niet: %s",
        "Style Tweaks": "Stijlaanpassingen",
        "Successfully reverted to rollback snapshot.": "Succesvol teruggekeerd naar herstelpunt.",
        "Undo Last Restore": "Laatste herstel ongedaan maken",
        "Undo Restore": "Herstel ongedaan maken",
        "Undo failed: ": "Ongedaan maken mislukt: ",
        "Upload failed (HTTP %s): %s": "Uploaden mislukt (HTTP %s): %s",
        "Uploading backup archive...": "Back-uparchief uploaden...",
        "User Plugins": "Gebruikersplug-ins",
        "[Up]  ..  (Parent folder)": "[Omhoog]  ..  (Bovenliggende map)",
        "btn_cancel": "Annuleren",
        "btn_close": "Sluiten",
        "btn_create": "Aanmaken",
        "btn_ok": "OK",
        "btn_restore": "Herstellen",
        "btn_settings": "Instellingen...",
        "plugin_desc": "Maak, beheer en herstel modulaire KOReader-back-ups met intelligente hardwarecompatibiliteit en noodherstel.",
        "plugin_name": "Apparaatback-up & Herstel"
    },
    'pl': {
        "\n\nSanitized %d hardware keys for device compatibility.": "\n\nOczyszczono %d kluczy sprzętowych dla zgodności urządzenia.",
        "(No subfolders)": "(Brak podfolderów)",
        "Archive: %s": "Archiwum: %s",
        "Are you sure you want to restore this backup?\n\nAn automatic safety rollback snapshot will be created before any files are updated.": "Czy na pewno chcesz przywrócić tę kopię?\n\nPrzed zmianą plików zostanie utworzony automatyczny punkt przywracania.",
        "Backup & Restore Settings": "Ustawienia kopii i przywracania",
        "Backup Folder:\n%s": "Folder kopii:\n%s",
        "Backup Name": "Nazwa kopii",
        "Backup created successfully!\n\nFile: %s\nSize: %s\nArchived files: %d": "Kopia zapasowa utworzona pomyślnie!\n\nPlik: %s\nRozmiar: %s\nZarchiwizowanych plików: %d",
        "Backup received successfully!\n\nFile: %s": "Kopia zapasowa odebrana pomyślnie!\n\nPlik: %s",
        "Backup restored successfully!": "Kopia zapasowa przywrócona pomyślnie!",
        "Backup: Beam to Another Device": "Kopia: Prześlij do innego urządzenia",
        "Backup: Create Backup": "Kopia: Utwórz kopię",
        "Backup: Open Manager": "Kopia: Otwórz menedżer",
        "Backup: Receive via Beam Code": "Kopia: Odbierz kodem Beam",
        "Backup: Restore Backup": "Kopia: Przywróć kopię",
        "Beam Relay Server URL": "Adres serwera Beam",
        "Beam Relay Server:\n%s": "Serwer Beam:\n%s",
        "Beam code expired or not found. Please verify the 6-digit code on the sending device.": "Kod Beam wygasł lub nie został znaleziony. Sprawdź 6-cyfrowy kod na urządzeniu nadawczym.",
        "Beam code must be exactly %d digits.": "Kod Beam musi mieć dokładnie %d cyfr.",
        "Beam code ready!": "Kod Beam gotowy!",
        "Beam reception failed:\n%s": "Odbiór Beam nie powiódł się:\n%s",
        "Beam to Another Device...": "Prześlij do innego urządzenia...",
        "Beam to Device": "Prześlij do urządzenia",
        "Beam to Device...": "Prześlij do urządzenia...",
        "Beam transfer canceled.": "Transfer Beam anulowany.",
        "Beam upload failed:\n%s": "Wysyłanie Beam nie powiodło się:\n%s",
        "Browse Folder": "Przeglądaj folder",
        "Browse Other Folder...": "Wybierz inny folder...",
        "Cancel": "Anuluj",
        "Cancel Transfer": "Anuluj transfer",
        "Choose Backup Folder": "Wybierz folder kopii",
        "Clean Slate (Remove unlisted plugins)": "Czysta instalacja (usuń niewymienione wtyczki)",
        "Clear All": "Odznacz wszystko",
        "Close": "Zamknij",
        "Code expires in 15 minutes\nSingle-use end-to-end encrypted": "Kod wygasa za 15 minut\nSzyfrowanie end-to-end, jednorazowe",
        "Connecting and downloading backup archive...": "Łączenie i pobieranie archiwum kopii...",
        "Connecting to Beam relay and downloading backup...\nPlease wait.": "Łączenie z serwerem Beam i pobieranie kopii...\nProszę czekać.",
        "Connecting to Beam relay...": "Łączenie z serwerem Beam...",
        "Corrupted or empty Beam payload.": "Uszkodzone lub puste dane Beam.",
        "Could not read file: %s": "Nie można odczytać pliku: %s",
        "Could not write file: %s": "Nie można zapisać pliku: %s",
        "Create": "Utwórz",
        "Create Backup": "Utwórz kopię",
        "Create Backup...": "Utwórz kopię...",
        "Create subfolder in '%s':": "Utwórz podfolder w '%s':",
        "Create, manage, and restore modular KOReader backups with intelligent cross-device hardware sanitization and disaster recovery.": "Twórz, zarządzaj i przywracaj modułowe kopie zapasowe KOReader z inteligentną adaptacją sprzętową i odzyskiwaniem awaryjnym.",
        "Creating backup archive...\nPlease wait.": "Tworzenie archiwum kopii zapasowej...\nProszę czekać.",
        "Default Format: .%s (Tap to toggle)": "Domyślny format: .%s (dotknij, aby zmienić)",
        "Delete": "Usuń",
        "Delete Backup": "Usuń kopię",
        "Delete backup '%s'?\nThis action cannot be undone.": "Usunąć kopię zapasową '%s'?\nTej operacji nie można cofnąć.",
        "Device Backup & Restore": "Kopia zapasowa i przywracanie",
        "Dictionaries & OCR Data": "Słowniki i dane OCR",
        "Done": "Gotowe",
        "Download failed (HTTP %s): %s": "Pobieranie nie powiodło się (HTTP %s): %s",
        "Encrypting backup and uploading to Beam relay...\nPlease wait.": "Szyfrowanie i wysyłanie na serwer Beam...\nProszę czekać.",
        "Encrypting backup archive...": "Szyfrowanie archiwum kopii...",
        "Enter custom filename (without extension):": "Wprowadź nazwę pliku (bez rozszerzenia):",
        "Enter the 6-digit Beam code from the sending device:": "Wpisz 6-cyfrowy kod Beam z urządzenia nadawczego:",
        "Extraction failed: %s": "Rozpakowywanie nie powiodło się: %s",
        "Failed to create backup:\n%s": "Błąd tworzenia kopii zapasowej:\n%s",
        "Failed to create folder.": "Błąd tworzenia folderu.",
        "Failed to inspect archive:\n": "Błąd sprawdzania archiwum:\n",
        "Fonts": "Czcionki",
        "Format: .%s": "Format: .%s",
        "HTTPS address of the ephemeral Beam relay:": "Adres HTTPS tymczasowego serwera Beam:",
        "Invalid Beam archive format.": "Nieprawidłowy format archiwum Beam.",
        "Invalid Beam code or corrupted data.": "Nieprawidłowy kod Beam lub uszkodzone dane.",
        "Invalid filename in Beam payload.": "Nieprawidłowa nazwa pliku w danych Beam.",
        "Manage Backups": "Zarządzaj kopiami",
        "Manage Backups...": "Zarządzaj kopiami...",
        "Name: %s": "Nazwa: %s",
        "New Folder": "Nowy folder",
        "Next": "Dalej",
        "No backup files found in:\n%s": "Nie znaleziono plików kopii w:\n%s",
        "No backup files found in:\n%s\n\nWould you like to browse a different folder?": "Nie znaleziono kopii w:\n%s\n\nCzy chcesz przejrzeć inny folder?",
        "No backup files found in:\n%s\n\nWould you like to create a new backup now?": "Nie znaleziono kopii w:\n%s\n\nCzy chcesz teraz utworzyć kopię?",
        "No backup files found.": "Nie znaleziono plików kopii zapasowych.",
        "No rollback snapshot available to undo.": "Brak punktu przywracania do wycofania zmian.",
        "Number of rolling backups to keep (0 = unlimited):": "Liczba zachowywanych kopii (0 = bez limitu):",
        "OK": "OK",
        "On the receiving device, open\n'Receive via Beam Code' and enter:": "Na urządzeniu odbiorczym otwórz\n'Odbierz kodem Beam' i wpisz:",
        "Patches": "Łatki",
        "Please enter a 6-digit Beam code.": "Wprowadź 6-cyfrowy kod Beam.",
        "Pre-flight check failed: %s": "Kontrola wstępna nie powiodła się: %s",
        "Preparing and encrypting backup archive...": "Przygotowywanie i szyfrowanie kopii...",
        "Previous": "Wstecz",
        "Reading History & Stats": "Historia i statystyki czytania",
        "Reading Progress & Notes": "Postęp czytania i notatki",
        "Receive & Restore": "Odbierz i przywróć",
        "Receive via Beam Code": "Odbierz kodem Beam",
        "Receive via Beam Code...": "Odbierz kodem Beam...",
        "Recommended": "Zalecane",
        "Registering code with Beam relay...": "Rejestrowanie kodu na serwerze Beam...",
        "Reset Default": "Przywróć domyślne",
        "Restart KOReader now to apply all changes?": "Zrestartować KOReader, aby zastosować zmiany?",
        "Restart later": "Zrestartuj później",
        "Restart now": "Zrestartuj teraz",
        "Restore Backup": "Przywróć kopię",
        "Restore Backup...": "Przywróć kopię...",
        "Restore Now": "Przywróć teraz",
        "Restore completed.": "Przywracanie zakończone.",
        "Restore failed: ": "Przywracanie nie powiodło się: ",
        "Restore: %s": "Przywróć: %s",
        "Restoring backup...\nPlease wait.": "Przywracanie kopii zapasowej...\nProszę czekać.",
        "Retention Limit": "Limit przechowywania",
        "Retention Limit: Keep newest %d backups": "Przechowywanie: zachowaj %d najnowszych kopii",
        "Revert to the pre-restore rollback snapshot?\n\nThis will undo the last restore and return your settings and patches to their prior state.\n\nKOReader will restart immediately.": "Przywrócić punkt sprzed odzyskiwania?\n\nCofnie to ostatnie przywracanie i przywróci poprzednie ustawienia i łatki.\n\nKOReader zrestartuje się natychmiast.",
        "Reverting to rollback snapshot...": "Wycofywanie do punktu przywracania...",
        "Sanitize Hardware Settings": "Oczyść ustawienia sprzętowe",
        "Save": "Zapisz",
        "Screensavers": "Wygaszacze ekranu",
        "Select All": "Zaznacz wszystko",
        "Select Backup Folder": "Wybierz folder kopii",
        "Select Backup to Beam": "Wybierz kopię do wysłania",
        "Select Backup to Restore": "Wybierz kopię do przywrócenia",
        "Select This Folder": "Wybierz ten folder",
        "Set Name": "Ustaw nazwę",
        "Settings & UI Gestures": "Ustawienia i gesty interfejsu",
        "Settings...": "Ustawienia...",
        "Source directory does not exist: %s": "Katalog źródłowy nie istnieje: %s",
        "Style Tweaks": "Dostosowanie stylu",
        "Successfully reverted to rollback snapshot.": "Pomyślnie wycofano zmiany z punktu przywracania.",
        "Undo Last Restore": "Cofnij ostatnie przywracanie",
        "Undo Restore": "Cofnij przywracanie",
        "Undo failed: ": "Cofanie nie powiodło się: ",
        "Upload failed (HTTP %s): %s": "Wysyłanie nie powiodło się (HTTP %s): %s",
        "Uploading backup archive...": "Wysyłanie archiwum kopii...",
        "User Plugins": "Wtyczki użytkownika",
        "[Up]  ..  (Parent folder)": "[Góra]  ..  (Folder nadrzędny)",
        "btn_cancel": "Anuluj",
        "btn_close": "Zamknij",
        "btn_create": "Utwórz",
        "btn_ok": "OK",
        "btn_restore": "Przywróć",
        "btn_settings": "Ustawienia...",
        "plugin_desc": "Twórz, zarządzaj i przywracaj modułowe kopie zapasowe KOReader z inteligentną adaptacją sprzętową i odzyskiwaniem awaryjnym.",
        "plugin_name": "Kopia zapasowa i przywracanie"
    },
    'ru': {
        "\n\nSanitized %d hardware keys for device compatibility.": "\n\nОчищено %d аппаратных параметров для совместимости.",
        "(No subfolders)": "(Нет подпапок)",
        "Archive: %s": "Архив: %s",
        "Are you sure you want to restore this backup?\n\nAn automatic safety rollback snapshot will be created before any files are updated.": "Вы уверены, что хотите восстановить эту резервную копию?\n\nПеред изменением файлов будет создан снимок безопасности.",
        "Backup & Restore Settings": "Настройки резервного копирования",
        "Backup Folder:\n%s": "Папка копий:\n%s",
        "Backup Name": "Имя копии",
        "Backup created successfully!\n\nFile: %s\nSize: %s\nArchived files: %d": "Резервная копия создана!\n\nФайл: %s\nРазмер: %s\nФайлов в архиве: %d",
        "Backup received successfully!\n\nFile: %s": "Резервная копия успешно получена!\n\nФайл: %s",
        "Backup restored successfully!": "Резервная копия успешно восстановлена!",
        "Backup: Beam to Another Device": "Копия: Передать на другое устройство",
        "Backup: Create Backup": "Копия: Создать копию",
        "Backup: Open Manager": "Копия: Открыть диспетчер",
        "Backup: Receive via Beam Code": "Копия: Получить по коду Beam",
        "Backup: Restore Backup": "Копия: Восстановить копию",
        "Beam Relay Server URL": "URL релей-сервера Beam",
        "Beam Relay Server:\n%s": "Сервер Beam:\n%s",
        "Beam code expired or not found. Please verify the 6-digit code on the sending device.": "Код Beam истек или не найден. Проверьте 6-значный код на устройстве-отправителе.",
        "Beam code must be exactly %d digits.": "Код Beam должен состоять ровно из %d цифр.",
        "Beam code ready!": "Код Beam готов!",
        "Beam reception failed:\n%s": "Ошибка приема Beam:\n%s",
        "Beam to Another Device...": "Передать на другое устройство...",
        "Beam to Device": "Передать на устройство",
        "Beam to Device...": "Передать на устройство...",
        "Beam transfer canceled.": "Передача Beam отменена.",
        "Beam upload failed:\n%s": "Ошибка отправки Beam:\n%s",
        "Browse Folder": "Обзор папки",
        "Browse Other Folder...": "Выбрать другую папку...",
        "Cancel": "Отмена",
        "Cancel Transfer": "Отменить передачу",
        "Choose Backup Folder": "Выбор папки для копий",
        "Clean Slate (Remove unlisted plugins)": "Чистая установка (удалить неуказанные плагины)",
        "Clear All": "Снять все",
        "Close": "Закрыть",
        "Code expires in 15 minutes\nSingle-use end-to-end encrypted": "Код действует 15 минут\nСквозное шифрование (одноразовый)",
        "Connecting and downloading backup archive...": "Подключение и загрузка архива...",
        "Connecting to Beam relay and downloading backup...\nPlease wait.": "Подключение к Beam и загрузка...\nПожалуйста, подождите.",
        "Connecting to Beam relay...": "Подключение к серверу Beam...",
        "Corrupted or empty Beam payload.": "Данные Beam повреждены или пусты.",
        "Could not read file: %s": "Не удалось прочитать файл: %s",
        "Could not write file: %s": "Не удалось записать файл: %s",
        "Create": "Создать",
        "Create Backup": "Создать копию",
        "Create Backup...": "Создать копию...",
        "Create subfolder in '%s':": "Создать подпапку в '%s':",
        "Create, manage, and restore modular KOReader backups with intelligent cross-device hardware sanitization and disaster recovery.": "Создание, управление и восстановление резервных копий KOReader с адаптацией настроек железа и защитой от сбоев.",
        "Creating backup archive...\nPlease wait.": "Создание архива резервной копии...\nПожалуйста, подождите.",
        "Default Format: .%s (Tap to toggle)": "Формат по умолчанию: .%s (нажмите для смены)",
        "Delete": "Удалить",
        "Delete Backup": "Удалить копию",
        "Delete backup '%s'?\nThis action cannot be undone.": "Удалить резервную копию '%s'?\nЭто действие необратимо.",
        "Device Backup & Restore": "Резервное копирование и восстановление",
        "Dictionaries & OCR Data": "Словари и данные OCR",
        "Done": "Готово",
        "Download failed (HTTP %s): %s": "Ошибка загрузки (HTTP %s): %s",
        "Encrypting backup and uploading to Beam relay...\nPlease wait.": "Шифрование и отправка на сервер Beam...\nПожалуйста, подождите.",
        "Encrypting backup archive...": "Шифрование архива резервной копии...",
        "Enter custom filename (without extension):": "Введите имя файла (без расширения):",
        "Enter the 6-digit Beam code from the sending device:": "Введите 6-значный код Beam с устройства-отправителя:",
        "Extraction failed: %s": "Ошибка распаковки: %s",
        "Failed to create backup:\n%s": "Не удалось создать резервную копию:\n%s",
        "Failed to create folder.": "Не удалось создать папку.",
        "Failed to inspect archive:\n": "Не удалось проверить архив:\n",
        "Fonts": "Шрифты",
        "Format: .%s": "Формат: .%s",
        "HTTPS address of the ephemeral Beam relay:": "HTTPS-адрес релей-сервера Beam:",
        "Invalid Beam archive format.": "Неверный формат архива Beam.",
        "Invalid Beam code or corrupted data.": "Неверный код Beam или поврежденные данные.",
        "Invalid filename in Beam payload.": "Недопустимое имя файла в данных Beam.",
        "Manage Backups": "Управление копиями",
        "Manage Backups...": "Управление копиями...",
        "Name: %s": "Имя: %s",
        "New Folder": "Новая папка",
        "Next": "Далее",
        "No backup files found in:\n%s": "Файлы резервных копий не найдены в:\n%s",
        "No backup files found in:\n%s\n\nWould you like to browse a different folder?": "Копии не найдены в:\n%s\n\nХотите выбрать другую папку?",
        "No backup files found in:\n%s\n\nWould you like to create a new backup now?": "Копии не найдены в:\n%s\n\nХотите создать копию прямо сейчас?",
        "No backup files found.": "Файлы резервных копий не найдены.",
        "No rollback snapshot available to undo.": "Нет доступного снимка для отката.",
        "Number of rolling backups to keep (0 = unlimited):": "Количество хранимых копий (0 = без ограничений):",
        "OK": "OK",
        "On the receiving device, open\n'Receive via Beam Code' and enter:": "На принимающем устройстве откройте\n'Получить по коду Beam' и введите:",
        "Patches": "Патчи",
        "Please enter a 6-digit Beam code.": "Пожалуйста, введите 6-значный код Beam.",
        "Pre-flight check failed: %s": "Предварительная проверка не удалась: %s",
        "Preparing and encrypting backup archive...": "Подготовка и шифрование архива...",
        "Previous": "Назад",
        "Reading History & Stats": "История чтения и статистика",
        "Reading Progress & Notes": "Прогресс чтения и заметки",
        "Receive & Restore": "Получить и восстановить",
        "Receive via Beam Code": "Получить по коду Beam",
        "Receive via Beam Code...": "Получить по коду Beam...",
        "Recommended": "Рекомендуемые",
        "Registering code with Beam relay...": "Регистрация кода на сервере Beam...",
        "Reset Default": "Сбросить",
        "Restart KOReader now to apply all changes?": "Перезапустить KOReader для применения изменений?",
        "Restart later": "Позже",
        "Restart now": "Сейчас",
        "Restore Backup": "Восстановить копию",
        "Restore Backup...": "Восстановить копию...",
        "Restore Now": "Восстановить сейчас",
        "Restore completed.": "Восстановление завершено.",
        "Restore failed: ": "Сбой восстановления: ",
        "Restore: %s": "Восстановление: %s",
        "Restoring backup...\nPlease wait.": "Восстановление данных...\nПожалуйста, подождите.",
        "Retention Limit": "Лимит хранения",
        "Retention Limit: Keep newest %d backups": "Хранение: сохранять %d последних копий",
        "Revert to the pre-restore rollback snapshot?\n\nThis will undo the last restore and return your settings and patches to their prior state.\n\nKOReader will restart immediately.": "Вернуться к снимку до восстановления?\n\nЭто отменит последнее восстановление и вернет настройки и патчи к прежнему состоянию.\n\nKOReader перезапустится.",
        "Reverting to rollback snapshot...": "Откат к снимку безопасности...",
        "Sanitize Hardware Settings": "Очищать настройки оборудования",
        "Save": "Сохранить",
        "Screensavers": "Заставки",
        "Select All": "Выбрать все",
        "Select Backup Folder": "Выбрать папку для копий",
        "Select Backup to Beam": "Выбрать копию для передачи",
        "Select Backup to Restore": "Выбрать копию для восстановления",
        "Select This Folder": "Выбрать эту папку",
        "Set Name": "Задать имя",
        "Settings & UI Gestures": "Настройки и жесты интерфейса",
        "Settings...": "Настройки...",
        "Source directory does not exist: %s": "Исходный каталог не существует: %s",
        "Style Tweaks": "Настройки стиля",
        "Successfully reverted to rollback snapshot.": "Откат к снимку безопасности успешно выполнен.",
        "Undo Last Restore": "Отменить восстановление",
        "Undo Restore": "Отменить восстановление",
        "Undo failed: ": "Ошибка отмены: ",
        "Upload failed (HTTP %s): %s": "Ошибка отправки (HTTP %s): %s",
        "Uploading backup archive...": "Загрузка архива на сервер...",
        "User Plugins": "Пользовательские плагины",
        "[Up]  ..  (Parent folder)": "[Вверх]  ..  (Родительская папка)",
        "btn_cancel": "Отмена",
        "btn_close": "Закрыть",
        "btn_create": "Создать",
        "btn_ok": "OK",
        "btn_restore": "Восстановить",
        "btn_settings": "Настройки...",
        "plugin_desc": "Создание, управление и восстановление резервных копий KOReader с адаптацией настроек железа и защитой от сбоев.",
        "plugin_name": "Резервное копирование и восстановление"
    },
    'ja': {
        "\n\nSanitized %d hardware keys for device compatibility.": "\n\nデバイス互換性のため %d 個のハードウェアキーを調整しました。",
        "(No subfolders)": "(サブフォルダなし)",
        "Archive: %s": "アーカイブ: %s",
        "Are you sure you want to restore this backup?\n\nAn automatic safety rollback snapshot will be created before any files are updated.": "このバックアップを復元してもよろしいですか？\n\nファイル更新前に自動で安全ロールバックスナップショットが作成されます。",
        "Backup & Restore Settings": "バックアップと復元の設定",
        "Backup Folder:\n%s": "バックアップ先フォルダ:\n%s",
        "Backup Name": "バックアップ名",
        "Backup created successfully!\n\nFile: %s\nSize: %s\nArchived files: %d": "バックアップを作成しました！\n\nファイル: %s\nサイズ: %s\n格納ファイル数: %d",
        "Backup received successfully!\n\nFile: %s": "バックアップを受信しました！\n\nファイル: %s",
        "Backup restored successfully!": "バックアップを正常に復元しました！",
        "Backup: Beam to Another Device": "バックアップ: 別端末へビーム送信",
        "Backup: Create Backup": "バックアップ: バックアップ作成",
        "Backup: Open Manager": "バックアップ: 管理画面を開く",
        "Backup: Receive via Beam Code": "バックアップ: ビームコードで受信",
        "Backup: Restore Backup": "バックアップ: バックアップ復元",
        "Beam Relay Server URL": "Beam 中継サーバー URL",
        "Beam Relay Server:\n%s": "Beam 中継サーバー:\n%s",
        "Beam code expired or not found. Please verify the 6-digit code on the sending device.": "ビームコードの有効期限が切れているか、見つかりません。送信側端末の6桁コードをご確認ください。",
        "Beam code must be exactly %d digits.": "ビームコードは正確に %d 桁である必要があります。",
        "Beam code ready!": "ビームコード準備完了！",
        "Beam reception failed:\n%s": "Beam 受信失敗:\n%s",
        "Beam to Another Device...": "別端末へビーム送信...",
        "Beam to Device": "端末へビーム送信",
        "Beam to Device...": "端末へビーム送信...",
        "Beam transfer canceled.": "Beam 送信がキャンセルされました。",
        "Beam upload failed:\n%s": "Beam アップロード失敗:\n%s",
        "Browse Folder": "フォルダを参照",
        "Browse Other Folder...": "別のフォルダを参照...",
        "Cancel": "キャンセル",
        "Cancel Transfer": "転送をキャンセル",
        "Choose Backup Folder": "バックアップフォルダを選択",
        "Clean Slate (Remove unlisted plugins)": "クリーン復元 (一覧外のプラグインを削除)",
        "Clear All": "すべて解除",
        "Close": "閉じる",
        "Code expires in 15 minutes\nSingle-use end-to-end encrypted": "コードの有効期限は15分です\n端末間暗号化・一回限り有効",
        "Connecting and downloading backup archive...": "接続してバックアップをダウンロード中...",
        "Connecting to Beam relay and downloading backup...\nPlease wait.": "Beam 中継に接続してダウンロード中...\nしばらくお待ちください。",
        "Connecting to Beam relay...": "Beam 中継サーバーへ接続中...",
        "Corrupted or empty Beam payload.": "Beam データが破損しているか空です。",
        "Could not read file: %s": "ファイルを読み込めませんでした: %s",
        "Could not write file: %s": "ファイルに書き込めませんでした: %s",
        "Create": "作成",
        "Create Backup": "バックアップ作成",
        "Create Backup...": "バックアップ作成...",
        "Create subfolder in '%s':": "'%s' 内にサブフォルダを作成:",
        "Create, manage, and restore modular KOReader backups with intelligent cross-device hardware sanitization and disaster recovery.": "端末間の設定調整機能と災害復旧を備えた、KOReader のモジュール式バックアップ作成・管理・復元機能。",
        "Creating backup archive...\nPlease wait.": "バックアップアーカイブを作成中...\nしばらくお待ちください。",
        "Default Format: .%s (Tap to toggle)": "標準形式: .%s (タップで切替)",
        "Delete": "削除",
        "Delete Backup": "バックアップを削除",
        "Delete backup '%s'?\nThis action cannot be undone.": "バックアップ '%s' を削除しますか？\nこの操作は取り消せません。",
        "Device Backup & Restore": "端末バックアップと復元",
        "Dictionaries & OCR Data": "辞書と OCR データ",
        "Done": "完了",
        "Download failed (HTTP %s): %s": "ダウンロード失敗 (HTTP %s): %s",
        "Encrypting backup and uploading to Beam relay...\nPlease wait.": "暗号化して Beam 中継へアップロード中...\nしばらくお待ちください。",
        "Encrypting backup archive...": "アーカイブを暗号化中...",
        "Enter custom filename (without extension):": "ファイル名を入力 (拡張子なし):",
        "Enter the 6-digit Beam code from the sending device:": "送信側端末に表示された6桁のビームコードを入力:",
        "Extraction failed: %s": "展開失敗: %s",
        "Failed to create backup:\n%s": "バックアップ作成失敗:\n%s",
        "Failed to create folder.": "フォルダ作成に失敗しました。",
        "Failed to inspect archive:\n": "アーカイブ確認失敗:\n",
        "Fonts": "フォント",
        "Format: .%s": "形式: .%s",
        "HTTPS address of the ephemeral Beam relay:": "一時的な Beam 中継サーバーの HTTPS アドレス:",
        "Invalid Beam archive format.": "無効な Beam アーカイブ形式です。",
        "Invalid Beam code or corrupted data.": "無効なビームコードまたは破損したデータです。",
        "Invalid filename in Beam payload.": "Beam データ内のファイル名が無効です。",
        "Manage Backups": "バックアップ管理",
        "Manage Backups...": "バックアップ管理...",
        "Name: %s": "名前: %s",
        "New Folder": "新規フォルダ",
        "Next": "次へ",
        "No backup files found in:\n%s": "次にバックアップファイルが見つかりません:\n%s",
        "No backup files found in:\n%s\n\nWould you like to browse a different folder?": "バックアップが見つかりません:\n%s\n\n別のフォルダを参照しますか？",
        "No backup files found in:\n%s\n\nWould you like to create a new backup now?": "バックアップが見つかりません:\n%s\n\n今すぐ新しく作成しますか？",
        "No backup files found.": "バックアップファイルが見つかりません。",
        "No rollback snapshot available to undo.": "取り消し可能なロールバックスナップショットがありません。",
        "Number of rolling backups to keep (0 = unlimited):": "保持する世代バックアップ数 (0 = 無制限):",
        "OK": "OK",
        "On the receiving device, open\n'Receive via Beam Code' and enter:": "受信側端末で「ビームコードで受信」を\n開き、次を入力してください:",
        "Patches": "パッチ",
        "Please enter a 6-digit Beam code.": "6桁のビームコードを入力してください。",
        "Pre-flight check failed: %s": "事前チェック失敗: %s",
        "Preparing and encrypting backup archive...": "バックアップの準備と暗号化中...",
        "Previous": "前へ",
        "Reading History & Stats": "読書履歴と統計",
        "Reading Progress & Notes": "読書進捗とメモ",
        "Receive & Restore": "受信して復元",
        "Receive via Beam Code": "ビームコードで受信",
        "Receive via Beam Code...": "ビームコードで受信...",
        "Recommended": "推奨",
        "Registering code with Beam relay...": "Beam 中継サーバーにコードを登録中...",
        "Reset Default": "初期値に戻す",
        "Restart KOReader now to apply all changes?": "変更を適用するため KOReader を今すぐ再起動しますか？",
        "Restart later": "後で再起動",
        "Restart now": "今すぐ再起動",
        "Restore Backup": "バックアップを復元",
        "Restore Backup...": "バックアップを復元...",
        "Restore Now": "今すぐ復元",
        "Restore completed.": "復元が完了しました。",
        "Restore failed: ": "復元失敗: ",
        "Restore: %s": "復元: %s",
        "Restoring backup...\nPlease wait.": "バックアップを復元中...\nしばらくお待ちください。",
        "Retention Limit": "保持上限",
        "Retention Limit: Keep newest %d backups": "保持上限: 最新の %d 個を保持",
        "Revert to the pre-restore rollback snapshot?\n\nThis will undo the last restore and return your settings and patches to their prior state.\n\nKOReader will restart immediately.": "復元前のロールバックスナップショットに戻しますか？\n\n前回の復元が取り消され、設定とパッチが復元前の状態に戻ります。\n\nKOReader は直ちに再起動します。",
        "Reverting to rollback snapshot...": "スナップショットへロールバック中...",
        "Sanitize Hardware Settings": "ハードウェア設定を自動調整",
        "Save": "保存",
        "Screensavers": "スクリーンセーバー",
        "Select All": "すべて選択",
        "Select Backup Folder": "バックアップフォルダを選択",
        "Select Backup to Beam": "送信するバックアップを選択",
        "Select Backup to Restore": "復元するバックアップを選択",
        "Select This Folder": "このフォルダを選択",
        "Set Name": "名前を設定",
        "Settings & UI Gestures": "設定と操作ジェスチャー",
        "Settings...": "設定...",
        "Source directory does not exist: %s": "コピー元ディレクトリが存在しません: %s",
        "Style Tweaks": "スタイル調整",
        "Successfully reverted to rollback snapshot.": "スナップショットへのロールバックが完了しました。",
        "Undo Last Restore": "前回の復元を取り消す",
        "Undo Restore": "復元の取り消し",
        "Undo failed: ": "取り消し失敗: ",
        "Upload failed (HTTP %s): %s": "アップロード失敗 (HTTP %s): %s",
        "Uploading backup archive...": "アーカイブをアップロード中...",
        "User Plugins": "ユーザープラグイン",
        "[Up]  ..  (Parent folder)": "[上へ]  ..  (親フォルダ)",
        "btn_cancel": "キャンセル",
        "btn_close": "閉じる",
        "btn_create": "作成",
        "btn_ok": "OK",
        "btn_restore": "復元",
        "btn_settings": "設定...",
        "plugin_desc": "端末間の設定調整機能と災害復旧を備えた、KOReader のモジュール式バックアップ作成・管理・復元機能。",
        "plugin_name": "端末バックアップと復元"
    },
    'ko': {
        "\n\nSanitized %d hardware keys for device compatibility.": "\n\n기기 호환성을 위해 하드웨어 설정 %d개를 정돈했습니다.",
        "(No subfolders)": "(하위 폴더 없음)",
        "Archive: %s": "압축 파일: %s",
        "Are you sure you want to restore this backup?\n\nAn automatic safety rollback snapshot will be created before any files are updated.": "이 백업을 복원하시겠습니까?\n\n파일이 업데이트되기 전에 자동 안전 롤백 스냅샷이 생성됩니다.",
        "Backup & Restore Settings": "백업 및 복원 설정",
        "Backup Folder:\n%s": "백업 폴더:\n%s",
        "Backup Name": "백업 이름",
        "Backup created successfully!\n\nFile: %s\nSize: %s\nArchived files: %d": "백업이 성공적으로 생성되었습니다!\n\n파일: %s\n크기: %s\n보관된 파일 수: %d",
        "Backup received successfully!\n\nFile: %s": "백업을 성공적으로 받았습니다!\n\n파일: %s",
        "Backup restored successfully!": "백업이 성공적으로 복원되었습니다!",
        "Backup: Beam to Another Device": "백업: 다른 기기로 전송",
        "Backup: Create Backup": "백업: 백업 생성",
        "Backup: Open Manager": "백업: 관리자 열기",
        "Backup: Receive via Beam Code": "백업: Beam 코드로 수신",
        "Backup: Restore Backup": "백업: 백업 복원",
        "Beam Relay Server URL": "Beam 중계 서버 URL",
        "Beam Relay Server:\n%s": "Beam 중계 서버:\n%s",
        "Beam code expired or not found. Please verify the 6-digit code on the sending device.": "Beam 코드가 만료되었거나 찾을 수 없습니다. 보내는 기기의 6자리 코드를 확인하세요.",
        "Beam code must be exactly %d digits.": "Beam 코드는 정확히 %d자리 숫자여야 합니다.",
        "Beam code ready!": "Beam 코드 준비 완료!",
        "Beam reception failed:\n%s": "Beam 수신 실패:\n%s",
        "Beam to Another Device...": "다른 기기로 전송...",
        "Beam to Device": "기기로 전송",
        "Beam to Device...": "기기로 전송...",
        "Beam transfer canceled.": "Beam 전송이 취소되었습니다.",
        "Beam upload failed:\n%s": "Beam 업로드 실패:\n%s",
        "Browse Folder": "폴더 찾아보기",
        "Browse Other Folder...": "다른 폴더 찾아보기...",
        "Cancel": "취소",
        "Cancel Transfer": "전송 취소",
        "Choose Backup Folder": "백업 폴더 선택",
        "Clean Slate (Remove unlisted plugins)": "클린 설치 (목록에 없는 플러그인 제거)",
        "Clear All": "모두 지우기",
        "Close": "닫기",
        "Code expires in 15 minutes\nSingle-use end-to-end encrypted": "코드는 15분 후 만료됩니다\n종단간 암호화 일회용",
        "Connecting and downloading backup archive...": "연결 및 백업 다운로드 중...",
        "Connecting to Beam relay and downloading backup...\nPlease wait.": "Beam 중계에 연결하여 백업 다운로드 중...\n잠시 기다려 주세요.",
        "Connecting to Beam relay...": "Beam 중계 서버에 연결 중...",
        "Corrupted or empty Beam payload.": "손상되었거나 비어 있는 Beam 데이터입니다.",
        "Could not read file: %s": "파일을 읽을 수 없습니다: %s",
        "Could not write file: %s": "파일을 쓸 수 없습니다: %s",
        "Create": "생성",
        "Create Backup": "백업 생성",
        "Create Backup...": "백업 생성...",
        "Create subfolder in '%s':": "'%s'에 하위 폴더 생성:",
        "Create, manage, and restore modular KOReader backups with intelligent cross-device hardware sanitization and disaster recovery.": "지능형 기기 간 하드웨어 호환성 정돈 및 재해 복구 기능을 갖춘 모듈식 KOReader 백업 생성, 관리 및 복원.",
        "Creating backup archive...\nPlease wait.": "백업 파일 생성 중...\n잠시 기다려 주세요.",
        "Default Format: .%s (Tap to toggle)": "기본 형식: .%s (누르면 전환)",
        "Delete": "삭제",
        "Delete Backup": "백업 삭제",
        "Delete backup '%s'?\nThis action cannot be undone.": "'%s' 백업을 삭제하시겠습니까?\n이 작업은 되돌릴 수 없습니다.",
        "Device Backup & Restore": "기기 백업 및 복원",
        "Dictionaries & OCR Data": "사전 및 OCR 데이터",
        "Done": "완료",
        "Download failed (HTTP %s): %s": "다운로드 실패 (HTTP %s): %s",
        "Encrypting backup and uploading to Beam relay...\nPlease wait.": "백업 암호화 및 Beam 업로드 중...\n잠시 기다려 주세요.",
        "Encrypting backup archive...": "백업 파일 암호화 중...",
        "Enter custom filename (without extension):": "사용자 지정 파일 이름 입력 (확장자 제외):",
        "Enter the 6-digit Beam code from the sending device:": "보내는 기기의 6자리 Beam 코드를 입력하세요:",
        "Extraction failed: %s": "압축 해제 실패: %s",
        "Failed to create backup:\n%s": "백업 생성 실패:\n%s",
        "Failed to create folder.": "폴더 생성 실패.",
        "Failed to inspect archive:\n": "백업 파일 확인 실패:\n",
        "Fonts": "글꼴",
        "Format: .%s": "형식: .%s",
        "HTTPS address of the ephemeral Beam relay:": "임시 Beam 중계 서버의 HTTPS 주소:",
        "Invalid Beam archive format.": "잘못된 Beam 압축 형식입니다.",
        "Invalid Beam code or corrupted data.": "잘못된 Beam 코드이거나 손상된 데이터입니다.",
        "Invalid filename in Beam payload.": "Beam 페이로드의 파일 이름이 잘못되었습니다.",
        "Manage Backups": "백업 관리",
        "Manage Backups...": "백업 관리...",
        "Name: %s": "이름: %s",
        "New Folder": "새 폴더",
        "Next": "다음",
        "No backup files found in:\n%s": "다음 위치에서 백업 파일을 찾을 수 없습니다:\n%s",
        "No backup files found in:\n%s\n\nWould you like to browse a different folder?": "백업을 찾을 수 없습니다:\n%s\n\n다른 폴더를 찾아보시겠습니까?",
        "No backup files found in:\n%s\n\nWould you like to create a new backup now?": "백업을 찾을 수 없습니다:\n%s\n\n지금 새 백업을 생성하시겠습니까?",
        "No backup files found.": "백업 파일이 없습니다.",
        "No rollback snapshot available to undo.": "되돌릴 수 있는 롤백 스냅샷이 없습니다.",
        "Number of rolling backups to keep (0 = unlimited):": "유지할 백업 수 (0 = 무제한):",
        "OK": "확인",
        "On the receiving device, open\n'Receive via Beam Code' and enter:": "받는 기기에서 'Beam 코드로 수신'을 열고\n다음을 입력하세요:",
        "Patches": "패치",
        "Please enter a 6-digit Beam code.": "6자리 Beam 코드를 입력해 주세요.",
        "Pre-flight check failed: %s": "사전 점검 실패: %s",
        "Preparing and encrypting backup archive...": "백업 파일 준비 및 암호화 중...",
        "Previous": "이전",
        "Reading History & Stats": "독서 기록 및 통계",
        "Reading Progress & Notes": "독서 진행률 및 메모",
        "Receive & Restore": "수신 및 복원",
        "Receive via Beam Code": "Beam 코드로 수신",
        "Receive via Beam Code...": "Beam 코드로 수신...",
        "Recommended": "권장",
        "Registering code with Beam relay...": "Beam 중계에 코드 등록 중...",
        "Reset Default": "기본값 복원",
        "Restart KOReader now to apply all changes?": "변경 사항을 적용하려면 KOReader를 지금 다시 시작하시겠습니까?",
        "Restart later": "나중에 다시 시작",
        "Restart now": "지금 다시 시작",
        "Restore Backup": "백업 복원",
        "Restore Backup...": "백업 복원...",
        "Restore Now": "지금 복원",
        "Restore completed.": "복원이 완료되었습니다.",
        "Restore failed: ": "복원 실패: ",
        "Restore: %s": "복원: %s",
        "Restoring backup...\nPlease wait.": "백업 복원 중...\n잠시 기다려 주세요.",
        "Retention Limit": "보관 제한",
        "Retention Limit: Keep newest %d backups": "보관 제한: 최신 %d개 백업 유지",
        "Revert to the pre-restore rollback snapshot?\n\nThis will undo the last restore and return your settings and patches to their prior state.\n\nKOReader will restart immediately.": "복원 전 롤백 스냅샷으로 되돌리시겠습니까?\n\n마지막 복원이 취소되고 설정과 패치가 이전 상태로 복구됩니다.\n\nKOReader가 즉시 다시 시작됩니다.",
        "Reverting to rollback snapshot...": "롤백 스냅샷으로 되돌리는 중...",
        "Sanitize Hardware Settings": "기기 하드웨어 설정 정돈",
        "Save": "저장",
        "Screensavers": "화면 보호기",
        "Select All": "모두 선택",
        "Select Backup Folder": "백업 폴더 선택",
        "Select Backup to Beam": "전송할 백업 선택",
        "Select Backup to Restore": "복원할 백업 선택",
        "Select This Folder": "이 폴더 선택",
        "Set Name": "이름 설정",
        "Settings & UI Gestures": "설정 및 제스처",
        "Settings...": "설정...",
        "Source directory does not exist: %s": "원본 디렉터리가 존재하지 않습니다: %s",
        "Style Tweaks": "스타일 미세 조정",
        "Successfully reverted to rollback snapshot.": "롤백 스냅샷으로 성공적으로 되돌렸습니다.",
        "Undo Last Restore": "마지막 복원 취소",
        "Undo Restore": "복원 취소",
        "Undo failed: ": "취소 실패: ",
        "Upload failed (HTTP %s): %s": "업로드 실패 (HTTP %s): %s",
        "Uploading backup archive...": "백업 파일 업로드 중...",
        "User Plugins": "사용자 플러그인",
        "[Up]  ..  (Parent folder)": "[위로]  ..  (상위 폴더)",
        "btn_cancel": "취소",
        "btn_close": "닫기",
        "btn_create": "생성",
        "btn_ok": "확인",
        "btn_restore": "복원",
        "btn_settings": "설정...",
        "plugin_desc": "지능형 기기 간 하드웨어 호환성 정돈 및 재해 복구 기능을 갖춘 모듈식 KOReader 백업 생성, 관리 및 복원.",
        "plugin_name": "기기 백업 및 복원"
    },
    'uk': {
        "\n\nSanitized %d hardware keys for device compatibility.": "\n\nОчищено %d апаратних параметрів для сумісності з пристроєм.",
        "(No subfolders)": "(Немає підпапок)",
        "Archive: %s": "Архів: %s",
        "Are you sure you want to restore this backup?\n\nAn automatic safety rollback snapshot will be created before any files are updated.": "Ви впевнені, що хочете відновити цю резервну копію?\n\nПеред зміною файлів буде створено знімок безпеки.",
        "Backup & Restore Settings": "Налаштування резервного копіювання",
        "Backup Folder:\n%s": "Папка копій:\n%s",
        "Backup Name": "Назва копії",
        "Backup created successfully!\n\nFile: %s\nSize: %s\nArchived files: %d": "Резервну копію успішно створено!\n\nФайл: %s\nРозмір: %s\nФайлів в архіві: %d",
        "Backup received successfully!\n\nFile: %s": "Резервну копію успішно отримано!\n\nФайл: %s",
        "Backup restored successfully!": "Резервну копію успішно відновлено!",
        "Backup: Beam to Another Device": "Копія: Надіслати на інший пристрій",
        "Backup: Create Backup": "Копія: Створити копію",
        "Backup: Open Manager": "Копія: Відкрити диспетчер",
        "Backup: Receive via Beam Code": "Копія: Отримати за кодом Beam",
        "Backup: Restore Backup": "Копія: Відновити копію",
        "Beam Relay Server URL": "URL релей-сервера Beam",
        "Beam Relay Server:\n%s": "Сервер Beam:\n%s",
        "Beam code expired or not found. Please verify the 6-digit code on the sending device.": "Код Beam застарів або не знайдений. Перевірте 6-значний код на пристрої-відправнику.",
        "Beam code must be exactly %d digits.": "Код Beam має містити рівно %d цифр.",
        "Beam code ready!": "Код Beam готовий!",
        "Beam reception failed:\n%s": "Помилка прийому Beam:\n%s",
        "Beam to Another Device...": "Надіслати на інший пристрій...",
        "Beam to Device": "Надіслати на пристрій",
        "Beam to Device...": "Надіслати на пристрій...",
        "Beam transfer canceled.": "Передачу Beam скасовано.",
        "Beam upload failed:\n%s": "Помилка вивантаження Beam:\n%s",
        "Browse Folder": "Огляд папки",
        "Browse Other Folder...": "Вибрати іншу папку...",
        "Cancel": "Скасувати",
        "Cancel Transfer": "Скасувати передачу",
        "Choose Backup Folder": "Вибір папки для копій",
        "Clean Slate (Remove unlisted plugins)": "Чисте відновлення (видалити неперелічені плагіни)",
        "Clear All": "Зняти всі",
        "Close": "Закрити",
        "Code expires in 15 minutes\nSingle-use end-to-end encrypted": "Код дійсний 15 хвилин\nНаскрізне шифрування (одноразовий)",
        "Connecting and downloading backup archive...": "Підключення та завантаження архіву...",
        "Connecting to Beam relay and downloading backup...\nPlease wait.": "Підключення до Beam та завантаження...\nБудь ласка, зачекайте.",
        "Connecting to Beam relay...": "Підключення до сервера Beam...",
        "Corrupted or empty Beam payload.": "Дані Beam пошкоджені або порожні.",
        "Could not read file: %s": "Не вдалося прочитати файл: %s",
        "Could not write file: %s": "Не вдалося записати файл: %s",
        "Create": "Створити",
        "Create Backup": "Створити копію",
        "Create Backup...": "Створити копію...",
        "Create subfolder in '%s':": "Створити підпапку в '%s':",
        "Create, manage, and restore modular KOReader backups with intelligent cross-device hardware sanitization and disaster recovery.": "Створюйте, керуйте та відновлюйте модульні резервні копії KOReader з інтелектуальною апаратною адаптацією та аварійним відновленням.",
        "Creating backup archive...\nPlease wait.": "Створення архіву резервної копії...\nБудь ласка, зачекайте.",
        "Default Format: .%s (Tap to toggle)": "Типовий формат: .%s (торкніться для зміни)",
        "Delete": "Видалити",
        "Delete Backup": "Видалити копію",
        "Delete backup '%s'?\nThis action cannot be undone.": "Видалити резервну копію '%s'?\nЦю дію не можна скасувати.",
        "Device Backup & Restore": "Резервне копіювання та відновлення",
        "Dictionaries & OCR Data": "Словники та дані OCR",
        "Done": "Готово",
        "Download failed (HTTP %s): %s": "Помилка завантаження (HTTP %s): %s",
        "Encrypting backup and uploading to Beam relay...\nPlease wait.": "Шифрування та передача на сервер Beam...\nБудь ласка, зачекайте.",
        "Encrypting backup archive...": "Шифрування архіву резервної копії...",
        "Enter custom filename (without extension):": "Введіть назву файлу (без розширення):",
        "Enter the 6-digit Beam code from the sending device:": "Введіть 6-значний код Beam із пристрою-відправника:",
        "Extraction failed: %s": "Помилка розпакування: %s",
        "Failed to create backup:\n%s": "Не вдалося створити резервну копію:\n%s",
        "Failed to create folder.": "Не вдалося створити папку.",
        "Failed to inspect archive:\n": "Не вдалося перевірити архів:\n",
        "Fonts": "Шрифти",
        "Format: .%s": "Формат: .%s",
        "HTTPS address of the ephemeral Beam relay:": "HTTPS-адреса тимчасового сервера Beam:",
        "Invalid Beam archive format.": "Неправильний формат архіву Beam.",
        "Invalid Beam code or corrupted data.": "Недійсний код Beam або пошкоджені дані.",
        "Invalid filename in Beam payload.": "Неприпустима назва файлу в даних Beam.",
        "Manage Backups": "Керування копіями",
        "Manage Backups...": "Керування копіями...",
        "Name: %s": "Назва: %s",
        "New Folder": "Нова папка",
        "Next": "Далі",
        "No backup files found in:\n%s": "Резервних копій не знайдено в:\n%s",
        "No backup files found in:\n%s\n\nWould you like to browse a different folder?": "Копій не знайдено в:\n%s\n\nБажаєте вибрати іншу папку?",
        "No backup files found in:\n%s\n\nWould you like to create a new backup now?": "Копій не знайдено в:\n%s\n\nБажаєте створити копію зараз?",
        "No backup files found.": "Резервних копій не знайдено.",
        "No rollback snapshot available to undo.": "Немає доступного знімка для відкату.",
        "Number of rolling backups to keep (0 = unlimited):": "Кількість копій для зберігання (0 = без обмежень):",
        "OK": "OK",
        "On the receiving device, open\n'Receive via Beam Code' and enter:": "На приймаючому пристрої відкрийте\n'Отримати за кодом Beam' і введіть:",
        "Patches": "Патчі",
        "Please enter a 6-digit Beam code.": "Будь ласка, введіть 6-значний код Beam.",
        "Pre-flight check failed: %s": "Попередня перевірка не вдалася: %s",
        "Preparing and encrypting backup archive...": "Підготовка та шифрування копії...",
        "Previous": "Назад",
        "Reading History & Stats": "Історія читання та статистика",
        "Reading Progress & Notes": "Прогрес читання та нотатки",
        "Receive & Restore": "Отримати та відновити",
        "Receive via Beam Code": "Отримати за кодом Beam",
        "Receive via Beam Code...": "Отримати за кодом Beam...",
        "Recommended": "Рекомендовані",
        "Registering code with Beam relay...": "Реєстрація коду на сервері Beam...",
        "Reset Default": "Скинути",
        "Restart KOReader now to apply all changes?": "Перезапустити KOReader для застосування змін?",
        "Restart later": "Пізніше",
        "Restart now": "Зараз",
        "Restore Backup": "Відновити копію",
        "Restore Backup...": "Відновити копію...",
        "Restore Now": "Відновити зараз",
        "Restore completed.": "Відновлення завершено.",
        "Restore failed: ": "Збій відновлення: ",
        "Restore: %s": "Відновлення: %s",
        "Restoring backup...\nPlease wait.": "Відновлення даних...\nБудь ласка, зачекайте.",
        "Retention Limit": "Ліміт зберігання",
        "Retention Limit: Keep newest %d backups": "Зберігання: залишати %d найновіших копій",
        "Revert to the pre-restore rollback snapshot?\n\nThis will undo the last restore and return your settings and patches to their prior state.\n\nKOReader will restart immediately.": "Повернутися до знімка до відновлення?\n\nЦе скасує останнє відновлення та поверне налаштування й патчі до попереднього стану.\n\nKOReader перезапуститься негайно.",
        "Reverting to rollback snapshot...": "Відкат до знімка безпеки...",
        "Sanitize Hardware Settings": "Очищати апаратні налаштування",
        "Save": "Зберегти",
        "Screensavers": "Заставки",
        "Select All": "Вибрати все",
        "Select Backup Folder": "Вибрати папку для копій",
        "Select Backup to Beam": "Вибрати копію для передачі",
        "Select Backup to Restore": "Вибрати копію для відновлення",
        "Select This Folder": "Вибрати цю папку",
        "Set Name": "Встановити назву",
        "Settings & UI Gestures": "Налаштування та жести інтерфейсу",
        "Settings...": "Налаштування...",
        "Source directory does not exist: %s": "Вихідний каталог не існує: %s",
        "Style Tweaks": "Налаштування стилю",
        "Successfully reverted to rollback snapshot.": "Успішно відновлено попередній стан зі знімка.",
        "Undo Last Restore": "Скасувати відновлення",
        "Undo Restore": "Скасувати відновлення",
        "Undo failed: ": "Помилка скасування: ",
        "Upload failed (HTTP %s): %s": "Помилка вивантаження (HTTP %s): %s",
        "Uploading backup archive...": "Вивантаження резервної копії...",
        "User Plugins": "Плагіни користувача",
        "[Up]  ..  (Parent folder)": "[Вгору]  ..  (Батьківська папка)",
        "btn_cancel": "Скасувати",
        "btn_close": "Закрити",
        "btn_create": "Створити",
        "btn_ok": "OK",
        "btn_restore": "Відновити",
        "btn_settings": "Налаштування...",
        "plugin_desc": "Створюйте, керуйте та відновлюйте модульні резервні копії KOReader з інтелектуальною апаратною адаптацією та аварійним відновленням.",
        "plugin_name": "Резервне копіювання та відновлення"
    }
}
